// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import XCTest

final class ComponentsuitestsUITests: XCTestCase {
  private let app = XCUIApplication()
  private func el(_ id: String) -> XCUIElement {
    app.descendants(matching: .any)[id]
  }
  private func byLabel(_ label: String) -> XCUIElement {
    app.descendants(matching: .any).matching(NSPredicate(format: "label == %@", label)).firstMatch
  }
  private func matchingId(_ glob: String) -> XCUIElementQuery {
    app.descendants(matching: .any).matching(NSPredicate(format: "identifier LIKE %@", glob))
  }

  func test_long_press_reveals_a_label() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "components"
    app.launch()

    XCTAssertFalse(el("comp.secret").exists)
    el("comp.longpress").press(forDuration: 0.6)

    // expect
    XCTAssertTrue(el("comp.secret").exists)
  }

  func test_in_app_alert_confirm() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "components"
    app.launch()

    el("comp.remove").tap()
    byLabel("Delete").tap()

    // expect
    XCTAssertTrue(el("comp.deleted").exists)
  }

  func test_swipe_records_left() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "components"
    app.launch()

    XCTAssertEqual(el("comp.swipeResult").value as? String, "none")
    el("comp.swipearea").swipeLeft()

    // expect
    XCTAssertEqual(el("comp.swipeResult").value as? String, "left")
  }

}
