// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import android.content.Context
import android.content.Intent
import android.util.Log
import android.view.KeyEvent
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.uiautomator.By
import androidx.test.uiautomator.BySelector
import androidx.test.uiautomator.Direction
import androidx.test.uiautomator.UiDevice
import androidx.test.uiautomator.UiObject2
import androidx.test.uiautomator.UiScrollable
import androidx.test.uiautomator.UiSelector
import androidx.test.uiautomator.Until
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TestRule
import org.junit.rules.TestWatcher
import org.junit.runner.Description
import org.junit.runner.RunWith
import java.io.File
import java.util.regex.Pattern

private const val PACKAGE = "com.bajutsu.showcase.android.compose"
private const val LAUNCH_TIMEOUT_MS = 20000L
private const val LAUNCH_ATTEMPTS = 2
private const val ACT_TIMEOUT_MS = 15000L
private const val TRACKING_KICK_ATTEMPTS = 3
private const val DIAGNOSTICS_DIR = "codegen-diagnostics"
private const val ADDITIONAL_OUTPUT_ARG = "additionalTestOutputDir"
private const val LOG_TAG = "BajutsuCodegen"

@RunWith(AndroidJUnit4::class)
class CodegenandroiduitestUITest {
  private val device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())

  // A timed-out wait says nothing about *why* nothing matched, so capture the state the
  // assertion was read from: the window hierarchy, the screen, and the accessibility window
  // list. Without them a failure is indistinguishable from a slow render and the only way
  // to investigate is to re-run until it happens again.
  @get:Rule
  val diagnostics: TestRule = object : TestWatcher() {
    override fun failed(error: Throwable, description: Description) {
      // methodName is a platform type, so Kotlin would insert an invisible null check here
      // and lose the evidence to a NullPointerException on the one path that needs it. Name
      // the fallback instead; displayName is populated for every description.
      dumpDiagnostics(description.methodName ?: description.displayName)
    }
  }

  // Every window the accessibility read channel reports, with the package its root belongs
  // to — the fact that separates "the element has not rendered yet" from "this app's
  // window is not in the tree at all".
  //
  // Never throws. The summary only ever explains a failure, and the callers below build it
  // into the message of the AssertionError they are about to raise — so a fault in reading
  // the windows would replace the failure's own message with a worse one.
  private fun windowSummary(): String = runCatching {
    val windows = InstrumentationRegistry.getInstrumentation().uiAutomation.windows
    if (windows.isEmpty()) {
      "<no accessibility windows>"
    } else {
      windows.joinToString("\n") { window ->
        "root=${window.root?.packageName ?: "<null>"} $window"
      }
    }
  }.getOrElse { "<unavailable: $it>" }

  // Every id `By.res` can currently match, read through the same matcher a selector goes
  // through — so it cannot disagree with what the failing wait searched. The hierarchy dump
  // does not substitute for it: dumpWindowHierarchy reports `resource-id` from the raw node,
  // which leaves a Compose testTag surfaced by testTagsAsResourceId blank there.
  // Never throws either: this goes into the dump below, so a fault reading the ids would
  // cost that evidence rather than be reported by it.
  private fun matchableIds(): String = runCatching {
    val ids = device.findObjects(By.res(Pattern.compile(".+")))
      .mapNotNull { it.resourceName }.distinct().sorted()
    if (ids.isEmpty()) "<none>" else ids.joinToString("\n")
  }.getOrElse { "<unavailable: $it>" }

  // One piece of evidence, written on its own: a throw here must not cost the other dumps,
  // and it must not pass silently either — a swallowed failure leaves the artifact simply
  // absent, on the very path meant to explain why something failed. Name the file and the
  // reason in logcat instead. takeScreenshot reports failure by returning false rather than
  // throwing, so its caller below turns that into a throw to reach the same log.
  private fun dump(file: File, write: (File) -> Unit) {
    runCatching { write(file) }.onFailure { Log.w(LOG_TAG, "could not write $file", it) }
  }

  // The window list is logged as well as written, so it survives even when the directory is
  // never collected off the device.
  private fun dumpDiagnostics(stem: String) {
    val summary = windowSummary()
    Log.w(LOG_TAG, "$stem failed; accessibility windows:\n$summary")
    // A null parent would make File(parent, …) a *relative* path, so the dumps would land
    // somewhere the harness never collects. The window list above is already in logcat.
    val parent = diagnosticsParent()
    if (parent == null) {
      Log.w(LOG_TAG, "no directory to write evidence to; see the window list above")
      return
    }
    val dir = File(parent, DIAGNOSTICS_DIR)
    if (!dir.isDirectory && !dir.mkdirs()) {
      Log.w(LOG_TAG, "could not create $dir; no evidence written")
      return
    }
    dump(File(dir, "$stem-windows.txt")) {
      it.writeText("accessibility windows:\n$summary\n\nmatchable ids:\n${matchableIds()}\n")
    }
    dump(File(dir, "$stem-hierarchy.xml")) { device.dumpWindowHierarchy(it) }
    dump(File(dir, "$stem-screen.png")) {
      if (!device.takeScreenshot(it)) error("takeScreenshot returned false")
    }
  }

  // The harness-collected directory when there is one, else the app's own external files
  // directory — a plain `am instrument` run (no Gradle) passes no argument, and a dump left
  // on the device still beats none. A blank argument counts as absent rather than as the
  // current directory, which `File("")` would otherwise resolve it to.
  private fun diagnosticsParent(): File? {
    val collected = InstrumentationRegistry.getArguments().getString(ADDITIONAL_OUTPUT_ARG)
    if (!collected.isNullOrBlank()) return File(collected)
    return InstrumentationRegistry.getInstrumentation().targetContext.getExternalFilesDir(null)
  }

  // Match the local id whether or not the app namespaces it with a `<package>:id/` prefix —
  // the reverse of the adb driver stripping that prefix (drivers/adb.py).
  private fun byId(id: String) =
    By.res(Pattern.compile("(.*:id/)?" + Pattern.quote(id)))

  // Match any of several candidate ids (a cross-platform selector, BE-0221) — the id form
  // this target's build actually surfaces (Compose: dotted; Views: underscore).
  private fun byAnyId(vararg ids: String) =
    By.res(Pattern.compile("(.*:id/)?(" + ids.joinToString("|") { Pattern.quote(it) } + ")"))

  // Provoke a window change so the accessibility framework has to re-report the window list,
  // and let the key press's own wait for the events it produces pace the recovery — never a
  // sleep. HOME is dispatched through the input pipeline rather than the accessibility one, so
  // it lands even while the accessibility view is stale, and it moves any foreground app off
  // screen. On the launcher it may produce only content changes, which the key press's own
  // wait accepts as well.
  //
  // Deliberately not wrapped in UiAutomation.executeAndWaitForEvent: pressHome already waits
  // through that same call, and the nested one would clear the event queue the outer wait is
  // watching, so the outer wait could only ever time out. The caller re-reads the window list
  // instead, which is the fact in question anyway.
  private fun kickWindowTracking(reason: String) {
    Log.w(LOG_TAG, "kicking accessibility window tracking with pressHome(): $reason")
    // pressHome reports a window event that never arrived by returning false, not by throwing,
    // and no event is the wedge's own symptom — so neither outcome may pass unrecorded.
    runCatching {
      if (!device.pressHome()) Log.w(LOG_TAG, "pressHome produced no window event")
    }.onFailure { Log.w(LOG_TAG, "pressHome failed", it) }
  }

  // Never throws. getWindows() raises IllegalStateException when the connection is not
  // established, so an unguarded read would replace the caller's named AssertionError with a
  // raw framework exception. Returning false collapses that fault together with an empty list,
  // which want opposite next steps — a kick recovers an empty list, an unestablished connection
  // it cannot — so the caller names which one it met by appending windowSummary() (never
  // throws either): "<no accessibility windows>" against "<unavailable: …>".
  private fun reportsWindows(): Boolean = runCatching {
    InstrumentationRegistry.getInstrumentation().uiAutomation.windows.isNotEmpty()
  }.getOrElse { Log.w(LOG_TAG, "could not read the window list", it); false }

  // One of two observed ways the app's window fails to reach the list, and the one that can be
  // caught before the launch wait spends its whole timeout: the list holds nothing at all. A CI
  // run logged exactly that — "no accessibility windows reported (attempt 1)" — and the
  // window change below recovered it.
  //
  // The other way is invisible here: the list is live and merely missing the app's window, which
  // reads as healthy to any is-it-empty check. launch() handles that one after its wait fails.
  // Both want the same remedy, because no timeout recovers a list that will not gain the window
  // on its own — only a window change can.
  private fun ensureWindowTracking() {
    for (attempt in 1..TRACKING_KICK_ATTEMPTS) {
      if (reportsWindows()) return
      kickWindowTracking("no accessibility windows reported (attempt $attempt)")
    }
    // The last kick would otherwise go unchecked — the loop provokes it and exits.
    if (!reportsWindows()) {
      throw AssertionError(
        "accessibility window tracking reported no usable window list after " +
          "$TRACKING_KICK_ATTEMPTS kick(s); windows:\n" + windowSummary()
      )
    }
  }

  // Launch (or relaunch) the app, forwarding launchEnv as intent extras (the reverse of the
  // adb backend's `am start --es`), and wait for its window to reach the accessibility tree —
  // a condition wait, never a sleep.
  //
  // Each attempt gets the whole LAUNCH_TIMEOUT_MS, so a merely slow cold start is waited out
  // rather than restarted: FLAG_ACTIVITY_CLEAR_TASK tears the activity down, so relaunching a
  // launch that was still on its way would send it back to the beginning and could starve an app
  // that needs more than one attempt's patience. Only a window that never arrives within the
  // full timeout is treated as stuck rather than slow, and only then is the intent re-issued.
  //
  // The wait is checked at all because falling through silently mis-attributes the failure to the
  // first action, which then times out against a screen the app never reached.
  private fun launch(extras: Map<String, String>) {
    val context = ApplicationProvider.getApplicationContext<Context>()
    for (attempt in 1..LAUNCH_ATTEMPTS) {
      // The window the wait below looks for can only be seen through the accessibility window
      // list, so check that the list is live before launching into it rather than reading the
      // silence as a slow app.
      ensureWindowTracking()
      val intent = context.packageManager.getLaunchIntentForPackage(PACKAGE)!!
        .apply { addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK) }
      for ((k, v) in extras) intent.putExtra(k, v)
      context.startActivity(intent)
      val by = By.pkg(PACKAGE).depth(0)
      if (device.wait(Until.hasObject(by), LAUNCH_TIMEOUT_MS)) {
        // The window wait proves a window from the package exists, not that it finished
        // drawing its first frame, so let the tree settle before any per-action clock starts.
        device.waitForIdle(LAUNCH_TIMEOUT_MS)
        return
      }
      // The summary, not just the miss. This is the line that identified the failure: a CI
      // run logged a LIVE two-window list here — SystemUI's status bar and a focused "Pixel
      // Launcher isn't responding" dialog — with the app's own window absent, 19s after
      // ActivityTaskManager had reported it Displayed. A focused system window keeps the app's
      // window out of what UiAutomation reports, so the app is drawn and foreground while every
      // selector searches a list it is not in.
      Log.w(LOG_TAG, "launch attempt $attempt saw no $PACKAGE window in "
        + "${LAUNCH_TIMEOUT_MS}ms; windows:\n" + windowSummary())
      // Hence the kick, and hence its not consulting the list: the list was neither empty nor
      // unreadable, so nothing above this point can detect the case. HOME dismisses whatever
      // holds focus, and the intent is re-issued into a screen the app can reach. In the run
      // above that recovery worked — attempt 2 came up and the test passed.
      //
      // Only while an attempt remains, though. HOME after the last one would leave every piece
      // of evidence below — the AssertionError's own window summary, the hierarchy dump, the
      // screenshot — describing the launcher, and a healthy launcher window list argues the
      // exact opposite of the failure it was collected to explain.
      if (attempt < LAUNCH_ATTEMPTS) {
        kickWindowTracking("launch attempt $attempt timed out")
      }
    }
    throw AssertionError(
      "launch: no $PACKAGE window in the accessibility tree after $LAUNCH_ATTEMPTS attempt(s) " +
        "of ${LAUNCH_TIMEOUT_MS}ms; windows:\n" + windowSummary()
    )
  }

  // Wait for an element before acting on it. findObject alone is a single-shot query with no
  // implicit wait, unlike the adb driver's tap() (its resolve step retries with a timeout),
  // so acting right after launch() or a UI transition can race the render — a condition
  // wait, never a fixed sleep. The failure names the windows it searched, so a missing id and
  // a missing app window are told apart from the message alone.
  private fun act(by: BySelector): UiObject2 {
    if (!device.wait(Until.hasObject(by), ACT_TIMEOUT_MS)) {
      throw AssertionError(
        "act: no element matched $by within ${ACT_TIMEOUT_MS}ms; windows:\n" + windowSummary()
      )
    }
    return device.findObject(by)
  }

  @Test
  fun test_search_filters_the_catalog() {
    val extras = mutableMapOf<String, String>()
    extras["SHOWCASE_UITEST"] = "1"
    launch(extras)

    act(byId("search")).click()
    assertTrue(device.wait(Until.hasObject(byId("search.field")), 10000L))
    assertTrue(device.wait(Until.hasObject(byId("search.row.1")), 5000L))
    act(byId("search.field")).text = "Horse 5"
    assertTrue(device.wait(Until.hasObject(byId("search.row.5")), 5000L))
    assertTrue(device.wait(Until.gone(byId("search.row.1")), 5000L))

    // expect
    assertEquals("1", device.findObject(byId("search.count")).contentDescription)
    assertTrue(device.hasObject(byId("search.row.5")))
    assertEquals(1, device.findObjects(By.res(Pattern.compile("(.*:id/)?search\\.row\\..*"))).size)
  }

}
