// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import android.content.Context
import android.content.Intent
import android.view.KeyEvent
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.uiautomator.By
import androidx.test.uiautomator.Direction
import androidx.test.uiautomator.UiDevice
import androidx.test.uiautomator.Until
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.util.regex.Pattern

private const val PACKAGE = "com.bajutsu.showcase.android.compose"
private const val LAUNCH_TIMEOUT_MS = 5000L

@RunWith(AndroidJUnit4::class)
class CodegenandroiduitestUITest {
  private val device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())

  // Match the local id whether or not the app namespaces it with a `<package>:id/` prefix —
  // the reverse of the adb driver stripping that prefix (drivers/adb.py).
  private fun byId(id: String) =
    By.res(Pattern.compile("(.*:id/)?" + Pattern.quote(id)))

  // Match any of several candidate ids (a cross-platform selector, BE-0221) — the id form
  // this target's build actually surfaces (Compose: dotted; Views: underscore).
  private fun byAnyId(vararg ids: String) =
    By.res(Pattern.compile("(.*:id/)?(" + ids.joinToString("|") { Pattern.quote(it) } + ")"))

  // Launch (or relaunch) the app, forwarding launchEnv as intent extras (the reverse of the
  // adb backend's `am start --es`); waits for the app's first window, never sleeps.
  private fun launch(extras: Map<String, String>) {
    val context = ApplicationProvider.getApplicationContext<Context>()
    val intent = context.packageManager.getLaunchIntentForPackage(PACKAGE)!!
      .apply { addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK) }
    for ((k, v) in extras) intent.putExtra(k, v)
    context.startActivity(intent)
    device.wait(Until.hasObject(By.pkg(PACKAGE).depth(0)), LAUNCH_TIMEOUT_MS)
  }

  @Test
  fun test_search_filters_the_catalog() {
    val extras = mutableMapOf<String, String>()
    extras["SHOWCASE_UITEST"] = "1"
    launch(extras)

    device.findObject(byId("search")).click()
    assertTrue(device.wait(Until.hasObject(byId("search.field")), 10000L))
    assertTrue(device.wait(Until.hasObject(byId("search.row.1")), 5000L))
    device.findObject(byId("search.field")).text = "Horse 5"
    assertTrue(device.wait(Until.hasObject(byId("search.row.5")), 5000L))
    assertTrue(device.wait(Until.gone(byId("search.row.1")), 5000L))

    // expect
    assertEquals("1", device.findObject(byId("search.count")).contentDescription)
    assertTrue(device.hasObject(byId("search.row.5")))
    assertEquals(1, device.findObjects(By.res(Pattern.compile("(.*:id/)?search\\.row\\..*"))).size)
  }

}
