"""Tests for Playwright code generation (structural scenario -> TypeScript)."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from bajutsu.cli import app
from bajutsu.codegen_playwright import describe_name_for, to_playwright
from bajutsu.scenario import load_scenarios

BASE = "http://localhost:3000"
runner = CliRunner()


def _gen(yaml: str, env: dict[str, str] | None = None, base_url: str = BASE) -> str:
    scenarios = load_scenarios(yaml)
    return to_playwright(scenarios, "Fixture", base_url, env or {})


def test_header_describe_and_base_url() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "import { test, expect } from '@playwright/test';" in code
    assert f"const BASE_URL = '{BASE}';" in code
    assert "test.describe('Fixture', () => {" in code
    assert "// Generated by bajutsu" in code


def test_test_per_scenario_uses_raw_name_and_goto() -> None:
    code = _gen("- name: long press reveals a label\n  steps:\n    - tap: { id: a }\n")
    assert "test('long press reveals a label', async ({ page }) => {" in code
    assert "await page.goto(BASE_URL);" in code


def test_tap_type_and_wait() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { id: onboarding.start }\n"
        "    - type: { text: a@b.com, into: { id: auth.email } }\n"
        "    - type: { text: hello }\n"
        "    - wait: { for: { id: home.title }, timeout: 5 }\n"
    )
    assert "await page.getByTestId('onboarding.start').click();" in code
    assert "await page.getByTestId('auth.email').fill('a@b.com');" in code
    assert "await page.keyboard.type('hello');" in code
    assert "await expect(page.getByTestId('home.title')).toBeVisible({ timeout: 5000 });" in code


def test_wait_until_gone() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - wait: { until: { gone: { id: spinner } }, timeout: 3 }\n"
    )
    assert "await expect(page.getByTestId('spinner')).toBeHidden({ timeout: 3000 });" in code


def test_long_press_emits_click_delay() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - longPress: { sel: { id: comp.longpress }, duration: 0.6 }\n"
    )
    assert "await page.getByTestId('comp.longpress').click({ delay: 600 });" in code


def test_swipe_direction_is_mouse_drag() -> None:
    code = _gen("- name: x\n  steps:\n    - swipe: { on: { id: list }, direction: up }\n")
    assert "const box = await page.getByTestId('list').boundingBox();" in code
    assert "await page.mouse.down();" in code
    assert "await page.mouse.move(cx + 0, cy + -100, { steps: 10 });" in code
    assert "await page.mouse.up();" in code


def test_swipe_from_to_is_todo() -> None:
    code = _gen("- name: x\n  steps:\n    - swipe: { from: [0.5, 0.8], to: [0.5, 0.2] }\n")
    assert "// TODO: coordinate swipe (from/to) is not generated" in code


def test_selector_label_traits_and_role() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { label: Submit }\n"
        "    - tap: { traits: [button] }\n"
        "    - tap: { label: Save, traits: [button] }\n"
    )
    assert "await page.getByText('Submit', { exact: true }).click();" in code
    assert "await page.getByRole('button').click();" in code
    assert "await page.getByRole('button', { name: 'Save', exact: true }).click();" in code


def test_id_matches_glob_maps_to_css_operators() -> None:
    suffix = _gen("- name: x\n  steps:\n    - tap: { idMatches: '*.submit' }\n")
    assert "await page.locator('[data-testid$=\".submit\"]').click();" in suffix
    prefix = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'list.row.*' }\n")
    assert "await page.locator('[data-testid^=\"list.row.\"]').click();" in prefix
    contains = _gen("- name: x\n  steps:\n    - tap: { idMatches: '*row*' }\n")
    assert "await page.locator('[data-testid*=\"row\"]').click();" in contains


def test_id_matches_complex_glob_is_todo() -> None:
    interior = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'a*b*c' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in interior
    charclass = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row[0-9]' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in charclass


def test_label_matches_is_a_regexp() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { labelMatches: '^Item ' }\n")
    assert "await page.getByText(/^Item /).click();" in code


def test_index_narrows_with_nth() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: row, index: 2 }\n")
    assert "await page.getByTestId('row').nth(2).click();" in code


def test_value_and_within_constraints_are_todo() -> None:
    with_value = _gen("- name: x\n  steps:\n    - tap: { id: f, value: '5' }\n")
    assert "// TODO: unsupported selector ('value':" in with_value
    with_within = _gen("- name: x\n  steps:\n    - tap: { id: c, within: { id: parent } }\n")
    assert "// TODO: unsupported selector ('within':" in with_within


def test_assertions_existence_and_negate() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - exists: { id: home.title }\n"
        "    - exists: { id: error.banner, negate: true }\n"
    )
    assert "await expect(page.getByTestId('home.title')).toBeVisible();" in code
    assert "await expect(page.getByTestId('error.banner')).toBeHidden();" in code


def test_assertions_value_label_state() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - value: { sel: { id: f }, equals: hi }\n"
        "    - value: { sel: { id: g }, contains: lo }\n"
        "    - label: { sel: { id: h }, equals: Hello }\n"
        "    - label: { sel: { id: i }, contains: ell }\n"
        "    - enabled: { id: btn }\n"
        "    - disabled: { id: btn2 }\n"
        "    - selected: { id: chk }\n"
    )
    assert "await expect(page.getByTestId('f')).toHaveValue('hi');" in code
    assert "await expect(page.getByTestId('g')).toHaveValue(/lo/);" in code
    assert "await expect(page.getByTestId('h')).toHaveText('Hello');" in code
    assert "await expect(page.getByTestId('i')).toContainText('ell');" in code
    assert "await expect(page.getByTestId('btn')).toBeEnabled();" in code
    assert "await expect(page.getByTestId('btn2')).toBeDisabled();" in code
    assert "await expect(page.getByTestId('chk')).toBeChecked();" in code


def test_assertions_count() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - count: { sel: { id: row }, equals: 3 }\n"
        "    - count: { sel: { id: row }, atLeast: 2 }\n"
        "    - count: { sel: { id: row }, atMost: 5 }\n"
    )
    assert "await expect(page.getByTestId('row')).toHaveCount(3);" in code
    assert "expect(await page.getByTestId('row').count()).toBeGreaterThanOrEqual(2);" in code
    assert "expect(await page.getByTestId('row').count()).toBeLessThanOrEqual(5);" in code


def test_relaunch_gotos_base_url() -> None:
    code = _gen("- name: x\n  steps:\n    - relaunch: {}\n")
    # one goto in setup, one for the relaunch
    assert code.count("await page.goto(BASE_URL);") == 2


def test_launch_env_seeds_localstorage() -> None:
    code = _gen(
        "- name: x\n  preconditions:\n    launchEnv: { B: '2' }\n  steps:\n    - tap: { id: a }\n",
        env={"A": "1"},
    )
    assert "await page.addInitScript(() => localStorage.setItem('A', '1'));" in code
    assert "await page.addInitScript(() => localStorage.setItem('B', '2'));" in code


def test_unsupported_constructs_emit_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - pinch: { sel: { id: photo }, scale: 2.0 }\n"
        "    - rotate: { sel: { id: photo }, radians: 1.5 }\n"
    )
    assert "// TODO: multi-touch (pinch) is not generated for web" in code
    assert "// TODO: multi-touch (rotate) is not generated for web" in code


def test_request_assertion_with_status_is_wait_for_response() -> None:
    # A matcher carrying `status` (a response field) must observe the response, not just the request.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { method: GET, path: /api/items, status: 200 }\n"
    )
    assert "await page.waitForResponse(r =>" in code
    assert "r.request().method() === 'GET'" in code
    assert "new URL(r.url()).pathname === '/api/items'" in code
    assert "r.status() === 200" in code


def test_request_assertion_without_response_field_is_wait_for_request() -> None:
    # No `status` (the only response-only field), so the request side alone is enough.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { method: POST, path: /api/login }\n"
    )
    assert "await page.waitForRequest(r =>" in code
    assert "r.method() === 'POST'" in code
    assert "new URL(r.url()).pathname === '/api/login'" in code


def test_request_assertion_url_and_url_matches() -> None:
    exact = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { url: 'https://api.test/v1/items' }\n"
    )
    assert "r.url() === 'https://api.test/v1/items'" in exact
    regex = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { urlMatches: '/items/[0-9]+' }\n"
    )
    assert "/\\/items\\/[0-9]+/.test(r.url())" in regex


def test_request_assertion_path_matches_is_regexp_over_pathname() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { pathMatches: '^/api/' }\n"
    )
    assert "/^\\/api\\//.test(new URL(r.url()).pathname)" in code


def test_request_assertion_body_matches_checks_request_post_data() -> None:
    # bodyMatches is a regex over the *request* body (runtime: match_request over ex.request_body),
    # so it maps to request.postData(), never the response body — even when status forces waitForResponse.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { path: /api/login, bodyMatches: 'token' }\n"
    )
    assert "/token/.test(r.postData() ?? '')" in code


def test_request_assertion_body_matches_with_status_uses_request_post_data() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { path: /api/login, status: 201, bodyMatches: 'token' }\n"
    )
    assert "await page.waitForResponse(r =>" in code
    assert "r.status() === 201" in code
    # Even under waitForResponse, the body predicate reads the *request* postData (runtime semantics).
    assert "/token/.test(r.request().postData() ?? '')" in code


def test_request_assertion_labels_the_endpoint() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { method: GET, path: /api/items, status: 200 }\n"
    )
    assert "// request GET /api/items status=200" in code


def test_wait_until_request_wraps_to_timeout() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/items, status: 200 } }, timeout: 4 }\n"
    )
    assert "await page.waitForResponse(r =>" in code
    assert "{ timeout: 4000 }" in code


def test_wait_until_request_without_status_is_wait_for_request() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/items } }, timeout: 2 }\n"
    )
    assert "await page.waitForRequest(r =>" in code
    assert "{ timeout: 2000 }" in code


def test_request_sequence_emits_one_wait_per_element_in_order() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - requestSequence:\n"
        "        - { path: /api/a }\n"
        "        - { path: /api/b, status: 200 }\n"
    )
    # Order is mirrored: /api/a's wait precedes /api/b's.
    a_idx = code.index("/api/a")
    b_idx = code.index("/api/b")
    assert a_idx < b_idx
    assert "// requestSequence /api/a → /api/b status=200" in code
    assert code.count("await page.waitForRequest(r =>") == 1  # /api/a (request only)
    assert code.count("await page.waitForResponse(r =>") == 1  # /api/b (carries status)


def test_response_schema_is_labeled_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - responseSchema: { request: { path: /api/items }, schema: items.json }\n"
    )
    assert "// TODO: responseSchema assertion (/api/items ~ items.json)" in code
    assert "JSON Schema" in code


def test_unsupported_selector_todo_names_field_and_reason() -> None:
    with_within = _gen("- name: x\n  steps:\n    - tap: { id: c, within: { id: parent } }\n")
    assert "// TODO: unsupported selector ('within':" in with_within
    with_value = _gen("- name: x\n  steps:\n    - tap: { id: f, value: '5' }\n")
    assert "// TODO: unsupported selector ('value':" in with_value
    interior_glob = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'a*b*c' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in interior_glob


def test_string_escaping() -> None:
    code = _gen('- name: x\n  steps:\n    - type: { text: "it\'s", into: { id: f } }\n')
    assert r"await page.getByTestId('f').fill('it\'s');" in code


def test_describe_name_for_humanizes_stem() -> None:
    assert describe_name_for("components") == "Components"
    assert describe_name_for("long_press-flow") == "Long Press Flow"
    assert describe_name_for("") == "Generated"


def _cli_setup(tmp_path: Path) -> tuple[Path, Path]:
    """A config with one web app (baseUrl) and one iOS app (bundleId), plus a scenario file."""
    cfg = tmp_path / "bajutsu.config.yaml"
    cfg.write_text(
        "targets:\n"
        "  web: { baseUrl: 'http://localhost:3000', idNamespaces: [home] }\n"
        "  ios: { bundleId: com.example.ios, idNamespaces: [home] }\n",
        encoding="utf-8",
    )
    scn = tmp_path / "s.yaml"
    scn.write_text("- name: demo\n  steps:\n    - tap: { id: home.title }\n", encoding="utf-8")
    return cfg, scn


def test_cli_emit_playwright_writes_spec(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    out = tmp_path / "demo.spec.ts"
    r = runner.invoke(
        app,
        [
            "codegen",
            str(scn),
            "--target",
            "web",
            "--emit",
            "playwright",
            "-o",
            str(out),
            "--config",
            str(cfg),
        ],
    )
    assert r.exit_code == 0, r.output
    code = out.read_text(encoding="utf-8")
    assert "const BASE_URL = 'http://localhost:3000';" in code
    assert "await page.getByTestId('home.title').click();" in code


def test_cli_emit_playwright_without_base_url_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "ios", "--emit", "playwright", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "baseUrl" in r.output


def test_cli_unsupported_emit_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "web", "--emit", "bogus", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "unsupported --emit" in r.output
