"""Tests for UI Automator code generation (structural scenario -> Kotlin)."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from bajutsu.cli import app
from bajutsu.codegen import EMIT_TARGETS, CodegenError, generate_test
from bajutsu.codegen.uiautomator import class_name_for, to_uiautomator
from bajutsu.config import load_config, resolve
from bajutsu.scenario import load_scenarios

PACKAGE = "com.example.app"
runner = CliRunner()


def _gen(yaml: str, env: dict[str, str] | None = None, package: str = PACKAGE) -> str:
    scenarios = load_scenarios(yaml)
    return to_uiautomator(scenarios, "ComponentsUITest", package, env or {})


def test_header_class_package_and_runner() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "// Generated by bajutsu" in code
    assert "import androidx.test.uiautomator.By" in code
    assert "@RunWith(AndroidJUnit4::class)" in code
    assert "class ComponentsUITest {" in code
    assert f'private const val PACKAGE = "{PACKAGE}"' in code


def test_test_per_scenario_uses_sanitized_name_and_launch() -> None:
    code = _gen("- name: open the filter sheet\n  steps:\n    - tap: { id: a }\n")
    assert "@Test" in code
    assert "fun test_open_the_filter_sheet() {" in code
    assert "launch(extras)" in code


def test_launch_env_merges_config_and_scenario_as_intent_extras() -> None:
    code = _gen(
        "- name: x\n  preconditions:\n    launchEnv: { SHOWCASE_TAB: log }\n"
        "  steps:\n    - tap: { id: a }\n",
        env={"SHOWCASE_UITEST": "1"},
    )
    assert "val extras = mutableMapOf<String, String>()" in code
    assert 'extras["SHOWCASE_UITEST"] = "1"' in code
    assert 'extras["SHOWCASE_TAB"] = "log"' in code


def test_tap_by_id_text_and_desc() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { id: onboarding.start }\n"
        "    - tap: { label: Submit }\n"
        "    - tap: { value: off }\n"
    )
    assert 'device.findObject(byId("onboarding.start")).click()' in code
    assert 'device.findObject(By.text("Submit")).click()' in code
    assert 'device.findObject(By.desc("off")).click()' in code


def test_type_into_sets_text_and_bare_type_is_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - type: { text: a@b.com, into: { id: auth.email } }\n"
        "    - type: { text: hello }\n"
    )
    assert 'device.findObject(byId("auth.email")).text = "a@b.com"' in code
    assert "// TODO: type without a target" in code


def test_text_editing_steps_emit_uiautomator_peers() -> None:
    # BE-0265: clear -> UiObject2.clear(), delete -> focus + N KEYCODE_DEL, select -> Ctrl+A,
    # copy -> Ctrl+C. The KeyEvent import backs the key codes.
    code = _gen(
        "- name: x\n  steps:\n"
        "    - clear: { into: { id: form.note } }\n"
        "    - delete: { into: { id: form.note }, count: 2 }\n"
        "    - select: { into: { id: form.note } }\n"
        "    - copy: {}\n"
    )
    assert "import android.view.KeyEvent" in code
    assert 'device.findObject(byId("form.note")).clear()' in code
    assert "repeat(2) { device.pressKeyCode(KeyEvent.KEYCODE_DEL) }" in code
    assert "device.pressKeyCode(KeyEvent.KEYCODE_A, KeyEvent.META_CTRL_ON)" in code
    assert "device.pressKeyCode(KeyEvent.KEYCODE_C, KeyEvent.META_CTRL_ON)" in code


def test_back_presses_the_system_key() -> None:
    # BE-0210: UI Automator has a native system back (peer of the adb driver's keyevent 4).
    code = _gen("- name: x\n  steps:\n    - back: {}\n")
    assert "device.pressBack()" in code
    assert "TODO" not in code


def test_wait_for_and_until_gone() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { for: { id: home.title }, timeout: 5 }\n"
        "    - wait: { until: { gone: { id: spinner } }, timeout: 3 }\n"
    )
    assert 'assertTrue(device.wait(Until.hasObject(byId("home.title")), 5000L))' in code
    assert 'assertTrue(device.wait(Until.gone(byId("spinner")), 3000L))' in code


def test_swipe_direction_and_from_to_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - swipe: { on: { id: list }, direction: up }\n"
        "    - swipe: { from: [0.5, 0.8], to: [0.5, 0.2] }\n"
    )
    assert 'device.findObject(byId("list")).swipe(Direction.UP, 0.75f)' in code
    assert "// TODO: coordinate swipe (from/to) is not generated" in code


def test_drag_maps_to_swipe_gesture() -> None:
    # `drag` (BE-0227) is an element-anchored pointer drag; UiObject2.swipe is a real drag, so it
    # emits the same primitive a directional swipe does.
    code = _gen("- name: x\n  steps:\n    - drag: { on: { id: divider }, direction: right }\n")
    assert 'device.findObject(byId("divider")).swipe(Direction.RIGHT, 0.75f)' in code


def test_long_press_pinch_and_unsupported_gestures() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - longPress: { sel: { id: comp.longpress }, duration: 0.6 }\n"
        "    - pinch: { sel: { id: photo }, scale: 2.0 }\n"
        "    - pinch: { sel: { id: photo }, scale: 0.5 }\n"
        "    - doubleTap: { id: comp.double }\n"
        "    - rotate: { sel: { id: photo }, radians: 1.5 }\n"
    )
    assert 'device.findObject(byId("comp.longpress")).longClick()' in code
    assert 'device.findObject(byId("photo")).pinchOpen(0.5f)' in code
    assert 'device.findObject(byId("photo")).pinchClose(0.5f)' in code
    assert "// TODO: doubleTap" in code
    assert "// TODO: rotate" in code


def test_relaunch_relaunches_with_extras() -> None:
    code = _gen("- name: x\n  steps:\n    - relaunch: {}\n")
    # `launch(extras)` appears once for the initial launch and once for the relaunch step.
    assert code.count("launch(extras)") == 2


def test_assertions_exist_label_value_state_and_count() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n"
        "  expect:\n"
        "    - exists: { id: home.title }\n"
        "    - exists: { id: spinner, negate: true }\n"
        "    - label: { sel: { id: greeting }, equals: Hello }\n"
        "    - label: { sel: { id: greeting }, contains: ell }\n"
        "    - value: { sel: { id: toggle }, equals: off }\n"
        "    - enabled: { id: submit }\n"
        "    - disabled: { id: cancel }\n"
        "    - selected: { id: tab.home }\n"
        "    - count: { sel: { id: row }, equals: 3 }\n"
        "    - count: { sel: { id: row }, atLeast: 1 }\n"
    )
    assert 'assertTrue(device.hasObject(byId("home.title")))' in code
    assert 'assertFalse(device.hasObject(byId("spinner")))' in code
    assert 'assertEquals("Hello", device.findObject(byId("greeting")).text)' in code
    assert 'assertTrue(device.findObject(byId("greeting")).text.contains("ell"))' in code
    assert 'assertEquals("off", device.findObject(byId("toggle")).contentDescription)' in code
    assert 'assertTrue(device.findObject(byId("submit")).isEnabled)' in code
    assert 'assertFalse(device.findObject(byId("cancel")).isEnabled)' in code
    assert 'assertTrue(device.findObject(byId("tab.home")).isSelected)' in code
    assert 'assertEquals(3, device.findObjects(byId("row")).size)' in code
    assert 'assertTrue(device.findObjects(byId("row")).size >= 1)' in code


def test_id_matches_glob_maps_to_res_pattern() -> None:
    # An fnmatch glob is a whole-string match, so By.res(Pattern) (Matcher.matches()) is faithful.
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row.*' }\n")
    assert 'By.res(Pattern.compile("(.*:id/)?row\\\\..*"))' in code


def test_id_candidate_list_emits_byanyid() -> None:
    # A cross-platform selector (BE-0221) targets either Android toolkit: uiautomator can't tell
    # whether the build surfaces the dotted (Compose) or underscore (Views) id, so it matches ANY
    # candidate via byAnyId rather than picking the first — otherwise a Views target never resolves.
    code = _gen("- name: x\n  steps:\n    - tap: { id: [stable.refresh, stable_refresh] }\n")
    assert 'device.findObject(byAnyId("stable.refresh", "stable_refresh")).click()' in code
    # The byAnyId helper is defined in the generated preamble.
    assert "private fun byAnyId(vararg ids: String)" in code


def test_id_matches_candidate_list_alternates_res_patterns() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: ['stable.row.*', 'stable_row_*'] }\n")
    assert (
        'By.res(Pattern.compile("(?:(.*:id/)?stable\\\\.row\\\\..*)|(?:(.*:id/)?stable_row_.*)"))'
        in code
    )


def test_id_matches_candidate_list_with_class_char_is_todo() -> None:
    # A `[...]` class in *any* candidate has no faithful regex (fnmatch-vs-regex negation differs),
    # so the whole selector conservatively degrades to a TODO — it must not emit a partial/wrong
    # alternation from only the clean candidates (BE-0221).
    code = _gen(
        "- name: x\n  steps:\n    - tap: { idMatches: ['stable.row[0-9]', 'stable_row_*'] }\n"
    )
    assert "// TODO: unsupported selector" in code
    assert (
        "(?:" not in code
    )  # no partial alternation emitted (only the byId/byAnyId preamble helpers)


def test_label_matches_substring_maps_to_contains_but_regex_is_todo() -> None:
    # `By.text(Pattern)` is a full-string match, unlike labelMatches' re.search — so a plain
    # substring maps to By.textContains, while a real regex (e.g. `^Item `) has no faithful form.
    substr = _gen("- name: x\n  steps:\n    - tap: { labelMatches: 'Item' }\n")
    assert 'device.findObject(By.textContains("Item")).click()' in substr
    regex = _gen("- name: x\n  steps:\n    - tap: { labelMatches: '^Item ' }\n")
    assert "// TODO: unsupported selector" in regex


def test_compound_selector_is_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: row, index: 2 }\n    - tap: { traits: [button] }\n"
    )
    assert code.count("// TODO: unsupported selector") == 2


def test_network_and_device_control_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - setLocation: { lat: 1.0, lon: 2.0 }\n"
        "  expect:\n    - request: { path: /api/x }\n"
    )
    assert "// TODO: setLocation" in code
    assert "// TODO: request assertion" in code


def test_permissions_field_emits_a_labeled_todo_per_service() -> None:
    code = _gen(
        "- name: x\n  permissions: { camera: grant, notifications: grant }\n  steps:\n"
        "    - tap: { id: a }\n"
    )
    assert "// TODO: permissions.camera (grant)" in code
    assert "// TODO: permissions.notifications (grant)" in code


def test_text_and_value_regex_and_contains() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n"
        "  expect:\n"
        "    - label: { sel: { id: greeting }, matches: '^Hello' }\n"
        "    - value: { sel: { id: toggle }, contains: of }\n"
        "    - count: { sel: { id: row }, atMost: 5 }\n"
    )
    assert 'assertTrue(device.findObject(byId("greeting")).text.contains(Regex("^Hello")))' in code
    assert 'assertTrue(device.findObject(byId("toggle")).contentDescription.contains("of"))' in code
    assert 'assertTrue(device.findObjects(byId("row")).size <= 5)' in code


def test_wait_until_request_and_settle_and_request_sequence_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/x } }, timeout: 5 }\n"
        "    - wait: { until: settled, timeout: 2 }\n"
        "  expect:\n"
        "    - requestSequence:\n        - { path: /a }\n        - { path: /b }\n"
    )
    assert "// TODO: wait until request" in code
    # `findObject` does not auto-wait, so a settle maps to `waitForIdle`, not a bare comment.
    assert "device.waitForIdle(2000L)" in code
    assert "// TODO: requestSequence assertion" in code


def test_device_control_and_helper_steps_are_labeled_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - push: { payload: {} }\n"
        "    - setClipboard: { text: hi }\n"
        "    - totp: { secret: GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ, into: { var: code } }\n"
        "    - email: { match: { subjectMatches: Verify }, extract: { var: pin, "
        "bodyMatches: 'PIN (\\d+)' }, timeout: 10 }\n"
        "    - background: {}\n"
    )
    assert "// TODO: push" in code
    assert "// TODO: setClipboard(text: " in code
    assert "// TODO: totp(into: code)" in code
    assert "// TODO: email(into: pin)" in code
    assert "// TODO: unsupported step" in code


def test_response_schema_and_visual_assertions_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - assert:\n"
        "        - responseSchema: { request: { path: /api/items }, schema: items.json }\n"
        "        - visual: { baseline: home.png }\n"
    )
    assert "// TODO: responseSchema assertion (/api/items)" in code
    assert "// TODO: unsupported assertion" in code


def test_compound_selector_in_wait_and_assertion_is_unsupported() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { for: { id: row, index: 0 }, timeout: 2 }\n"
        "  expect:\n    - label: { sel: { traits: [button] }, equals: OK }\n"
    )
    assert code.count("// TODO: unsupported selector") == 2


def test_compound_selector_in_gone_count_state_is_unsupported() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { gone: { id: row, index: 0 } }, timeout: 2 }\n"
        "  expect:\n"
        "    - exists: { traits: [button] }\n"
        "    - count: { sel: { traits: [button] }, equals: 1 }\n"
        "    - enabled: { id: submit, index: 0 }\n"
    )
    assert code.count("// TODO: unsupported selector") == 4


def test_id_matches_char_class_is_unsupported() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row[0-9]' }\n")
    assert "// TODO: unsupported selector" in code


def test_string_literals_escape_kotlin_specials() -> None:
    # Kotlin forbids a raw line break in a "…" literal and reads `$` as a template start, so both
    # must be escaped or the generated file would not compile.
    code = _gen('- name: x\n  steps:\n    - type: { text: "a$b\\nc", into: { id: f } }\n')
    assert r'device.findObject(byId("f")).text = "a\$b\nc"' in code


def test_class_name_for_stem() -> None:
    assert class_name_for("login_flow") == "LoginFlowUITest"
    assert class_name_for("!!!") == "GeneratedUITest"
    # A digit-leading stem must not produce an identifier that starts with a digit — that is not a
    # valid Kotlin class name and would fail to compile.
    assert class_name_for("2fa_flow") == "_2FaFlowUITest"


def test_scenario_name_sanitizing_edges() -> None:
    assert "fun test_scenario()" in _gen("- name: '!!!'\n  steps:\n    - tap: { id: a }\n")
    assert "fun test__2fa()" in _gen("- name: '2fa'\n  steps:\n    - tap: { id: a }\n")


def test_uiautomator_is_a_registered_emit_target() -> None:
    assert "uiautomator" in EMIT_TARGETS


def test_generate_test_on_android_target_returns_kt_file() -> None:
    eff = resolve(load_config("targets:\n  droid:\n    package: com.example.app\n"), "droid")
    code, filename = generate_test(
        "uiautomator", load_scenarios("- name: x\n  steps:\n    - tap: { id: a }\n"), "login", eff
    )
    assert filename == "LoginUITest.kt"
    assert "class LoginUITest {" in code


def test_generate_test_uiautomator_on_non_android_target_fails() -> None:
    eff = resolve(load_config("targets:\n  web:\n    baseUrl: http://localhost:3000\n"), "web")
    with pytest.raises(CodegenError, match="Android target"):
        generate_test(
            "uiautomator", load_scenarios("- name: x\n  steps:\n    - tap: { id: a }\n"), "x", eff
        )


def _cli_setup(tmp_path: Path) -> tuple[Path, Path]:
    """A config with one Android app (package) and one web app (baseUrl), plus a scenario file."""
    cfg = tmp_path / "bajutsu.config.yaml"
    cfg.write_text(
        "targets:\n"
        "  droid: { package: com.example.app, idNamespaces: [home] }\n"
        "  web: { baseUrl: 'http://localhost:3000', idNamespaces: [home] }\n",
        encoding="utf-8",
    )
    scn = tmp_path / "s.yaml"
    scn.write_text("- name: demo\n  steps:\n    - tap: { id: home.title }\n", encoding="utf-8")
    return cfg, scn


def test_cli_emit_uiautomator_writes_kt(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    out = tmp_path / "Demo.kt"
    r = runner.invoke(
        app,
        [
            "codegen",
            str(scn),
            "--target",
            "droid",
            "--emit",
            "uiautomator",
            "-o",
            str(out),
            "--config",
            str(cfg),
        ],
    )
    assert r.exit_code == 0, r.output
    code = out.read_text(encoding="utf-8")
    assert 'private const val PACKAGE = "com.example.app"' in code
    assert 'device.findObject(byId("home.title")).click()' in code


def test_cli_emit_uiautomator_without_package_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "web", "--emit", "uiautomator", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "package" in r.output


def test_manual_step_is_a_labeled_todo() -> None:
    code = _gen('- name: x\n  steps:\n    - manual: { label: "solve the CAPTCHA" }\n')
    assert "// TODO: manual step — solve the CAPTCHA" in code
    assert "no deterministic run-time equivalent" in code


def test_runtime_only_constructs_fail_loudly() -> None:
    # BE-0297: the fail-loudly guard lives in the shared walk (common.py), so `if` / `forEach` /
    # `extract` are rejected identically here as for XCUITest — never a silent no-op stub.
    with pytest.raises(CodegenError, match="`forEach` control-flow step"):
        _gen(
            "- name: x\n  steps:\n"
            "    - forEach:\n"
            "        sel: { idMatches: 'row.*' }\n"
            "        as: row\n"
            "        steps:\n"
            "          - tap: { id: '${vars.row}' }\n"
        )
