"""Tests for Playwright code generation (structural scenario -> TypeScript)."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from bajutsu.cli import app
from bajutsu.codegen.playwright import describe_name_for, to_playwright
from bajutsu.scenario import load_scenarios

BASE = "http://localhost:3000"
runner = CliRunner()


def _gen(yaml: str, env: dict[str, str] | None = None, base_url: str = BASE) -> str:
    scenarios = load_scenarios(yaml)
    return to_playwright(scenarios, "Fixture", base_url, env or {})


def test_header_describe_and_base_url() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "import { test, expect } from '@playwright/test';" in code
    assert f"const BASE_URL = '{BASE}';" in code
    assert "test.describe('Fixture', () => {" in code
    assert "// Generated by bajutsu" in code


def test_test_per_scenario_uses_raw_name_and_goto() -> None:
    code = _gen("- name: long press reveals a label\n  steps:\n    - tap: { id: a }\n")
    assert "test('long press reveals a label', async ({ page }) => {" in code
    assert "await page.goto(BASE_URL);" in code


def test_tap_type_and_wait() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { id: onboarding.start }\n"
        "    - type: { text: a@b.com, into: { id: auth.email } }\n"
        "    - type: { text: hello }\n"
        "    - wait: { for: { id: home.title }, timeout: 5 }\n"
    )
    assert "await page.getByTestId('onboarding.start').click();" in code
    assert "await page.getByTestId('auth.email').fill('a@b.com');" in code
    assert "await page.keyboard.type('hello');" in code
    assert "await expect(page.getByTestId('home.title')).toBeVisible({ timeout: 5000 });" in code


def test_text_editing_steps_emit_web_peers() -> None:
    # BE-0265: clear -> Locator.clear(), select -> selectText(), delete -> focus + N backspaces,
    # copy -> Control+c on the keyboard.
    code = _gen(
        "- name: x\n  steps:\n"
        "    - clear: { into: { id: form.note } }\n"
        "    - delete: { into: { id: form.note }, count: 2 }\n"
        "    - select: { into: { id: form.note } }\n"
        "    - copy: {}\n"
    )
    assert "await page.getByTestId('form.note').clear();" in code
    assert "await page.getByTestId('form.note').focus();" in code
    assert code.count("await page.keyboard.press('Backspace');") == 2
    assert "await page.getByTestId('form.note').selectText();" in code
    assert "await page.keyboard.press('Control+c');" in code


def test_wait_until_gone() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - wait: { until: { gone: { id: spinner } }, timeout: 3 }\n"
    )
    assert "await expect(page.getByTestId('spinner')).toBeHidden({ timeout: 3000 });" in code


def test_back_goes_back_in_history() -> None:
    # BE-0210: the web `back` step is browser history — emitted faithfully, not an unlabeled TODO.
    code = _gen("- name: x\n  steps:\n    - back: {}\n")
    assert "await page.goBack();" in code
    assert "TODO" not in code


def test_long_press_emits_click_delay() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - longPress: { sel: { id: comp.longpress }, duration: 0.6 }\n"
    )
    assert "await page.getByTestId('comp.longpress').click({ delay: 600 });" in code


def test_swipe_direction_is_wheel_scroll() -> None:
    # A directional swipe means "scroll": the web emitter wheels over the element (BE-0227), the
    # primitive that actually scrolls a page — not the old mouse drag, which left the page inert.
    code = _gen("- name: x\n  steps:\n    - swipe: { on: { id: list }, direction: up }\n")
    assert "const box = await page.getByTestId('list').boundingBox();" in code
    assert "await page.mouse.move(cx, cy);" in code
    # `up` pushes the surface up, so the page scrolls down: positive delta_y.
    assert "await page.mouse.wheel(0, 100);" in code
    assert "await page.mouse.down();" not in code


def test_swipe_from_to_is_todo() -> None:
    code = _gen("- name: x\n  steps:\n    - swipe: { from: [0.5, 0.8], to: [0.5, 0.2] }\n")
    assert "// TODO: coordinate swipe (from/to) is not generated" in code


def test_drag_direction_is_a_mouse_drag() -> None:
    # A `drag` (BE-0227) is a real pointer drag of the element — move/down/move/up — not a wheel;
    # `right` drags the pointer right (positive dx), so a grabbed handle actually moves.
    code = _gen("- name: x\n  steps:\n    - drag: { on: { id: divider }, direction: right }\n")
    assert "const box = await page.getByTestId('divider').boundingBox();" in code
    assert "await page.mouse.down();" in code
    assert "await page.mouse.move(cx + 100, cy + 0, { steps: 10 });" in code
    assert "await page.mouse.up();" in code
    assert "page.mouse.wheel" not in code


def test_selector_label_traits_and_role() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { label: Submit }\n"
        "    - tap: { traits: [button] }\n"
        "    - tap: { label: Save, traits: [button] }\n"
    )
    assert "await page.getByText('Submit', { exact: true }).click();" in code
    assert "await page.getByRole('button').click();" in code
    assert "await page.getByRole('button', { name: 'Save', exact: true }).click();" in code


def test_id_candidate_list_emits_primary_candidate() -> None:
    # A generated test targets one platform (web here), so a cross-platform candidate list (BE-0221)
    # emits its primary (first, dotted SPEC) candidate — the id the web build surfaces as data-testid.
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { id: [stable.refresh, stable_refresh] }\n"
        "    - tap: { idMatches: [list.row.*, list_row_*] }\n"
    )
    assert "await page.getByTestId('stable.refresh').click();" in code
    assert "await page.locator('[data-testid^=\"list.row.\"]').click();" in code
    assert "stable_refresh" not in code  # the underscore alternate is not emitted for web


def test_id_matches_glob_maps_to_css_operators() -> None:
    suffix = _gen("- name: x\n  steps:\n    - tap: { idMatches: '*.submit' }\n")
    assert "await page.locator('[data-testid$=\".submit\"]').click();" in suffix
    prefix = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'list.row.*' }\n")
    assert "await page.locator('[data-testid^=\"list.row.\"]').click();" in prefix
    contains = _gen("- name: x\n  steps:\n    - tap: { idMatches: '*row*' }\n")
    assert "await page.locator('[data-testid*=\"row\"]').click();" in contains


def test_id_matches_complex_glob_is_todo() -> None:
    interior = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'a*b*c' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in interior
    charclass = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row[0-9]' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in charclass


def test_label_matches_is_a_regexp() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { labelMatches: '^Item ' }\n")
    assert "await page.getByText(/^Item /).click();" in code


def test_index_narrows_with_nth() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: row, index: 2 }\n")
    assert "await page.getByTestId('row').nth(2).click();" in code


def test_assertions_existence_and_negate() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - exists: { id: home.title }\n"
        "    - exists: { id: error.banner, negate: true }\n"
    )
    assert "await expect(page.getByTestId('home.title')).toBeVisible();" in code
    assert "await expect(page.getByTestId('error.banner')).toBeHidden();" in code


def test_assertions_value_label_state() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - value: { sel: { id: f }, equals: hi }\n"
        "    - value: { sel: { id: g }, contains: lo }\n"
        "    - label: { sel: { id: h }, equals: Hello }\n"
        "    - label: { sel: { id: i }, contains: ell }\n"
        "    - enabled: { id: btn }\n"
        "    - disabled: { id: btn2 }\n"
        "    - selected: { id: chk }\n"
    )
    assert "await expect(page.getByTestId('f')).toHaveValue('hi');" in code
    assert "await expect(page.getByTestId('g')).toHaveValue(/lo/);" in code
    assert "await expect(page.getByTestId('h')).toHaveText('Hello');" in code
    assert "await expect(page.getByTestId('i')).toContainText('ell');" in code
    assert "await expect(page.getByTestId('btn')).toBeEnabled();" in code
    assert "await expect(page.getByTestId('btn2')).toBeDisabled();" in code
    assert "await expect(page.getByTestId('chk')).toBeChecked();" in code


def test_assertions_count() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - count: { sel: { id: row }, equals: 3 }\n"
        "    - count: { sel: { id: row }, atLeast: 2 }\n"
        "    - count: { sel: { id: row }, atMost: 5 }\n"
    )
    assert "await expect(page.getByTestId('row')).toHaveCount(3);" in code
    assert "expect(await page.getByTestId('row').count()).toBeGreaterThanOrEqual(2);" in code
    assert "expect(await page.getByTestId('row').count()).toBeLessThanOrEqual(5);" in code


def test_relaunch_gotos_base_url() -> None:
    code = _gen("- name: x\n  steps:\n    - relaunch: {}\n")
    # one goto in setup, one for the relaunch
    assert code.count("await page.goto(BASE_URL);") == 2


def test_launch_env_seeds_localstorage() -> None:
    code = _gen(
        "- name: x\n  preconditions:\n    launchEnv: { B: '2' }\n  steps:\n    - tap: { id: a }\n",
        env={"A": "1"},
    )
    assert "await page.addInitScript(() => localStorage.setItem('A', '1'));" in code
    assert "await page.addInitScript(() => localStorage.setItem('B', '2'));" in code


def test_unsupported_constructs_emit_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - pinch: { sel: { id: photo }, scale: 2.0 }\n"
        "    - rotate: { sel: { id: photo }, radians: 1.5 }\n"
    )
    assert "// TODO: multi-touch (pinch) is not generated for web" in code
    assert "// TODO: multi-touch (rotate) is not generated for web" in code


def test_network_assertions_install_an_exchange_recorder_before_navigation() -> None:
    # Network assertions are evaluated over the exchanges observed *so far* (like the runner's
    # collector), so the test records finished exchanges up front rather than only waiting for
    # future traffic. The recorder is installed before navigation, so it captures the whole flow.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { path: /api/items }\n"
    )
    # 'requestfinished' is the same event the runtime web collector hooks (web_network.py), so the
    # generated recorder records the same finished exchanges (and status=null when there's no
    # response) rather than the earlier-firing 'response'.
    assert "page.on('requestfinished', async req => {" in code
    assert "status: res ? res.status() : null" in code
    assert "exchanges.push({" in code
    assert code.index("page.on('requestfinished'") < code.index("await page.goto(BASE_URL)")


def test_no_recorder_without_network_constructs() -> None:
    # A scenario that asserts nothing over the network must not carry the recorder scaffold.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n    - exists: { id: t }\n")
    assert "page.on('requestfinished'" not in code
    assert "exchanges" not in code


def test_request_assertion_evaluates_over_recorded_exchanges() -> None:
    # A `request` assertion is a point-in-time check over the exchanges observed so far — never a
    # `waitForResponse`, which would miss traffic that already happened during the steps.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { method: GET, path: /api/items, status: 200 }\n"
    )
    assert "expect(exchanges.some(e =>" in code
    assert "e.method === 'GET'" in code
    assert "new URL(e.url).pathname === '/api/items'" in code
    assert "e.status === 200" in code
    assert "// request GET /api/items status=200" in code
    assert "waitForResponse" not in code and "waitForRequest" not in code


def test_request_assertion_with_count_checks_exact_match_count() -> None:
    # `count` is part of the `request` assertion's semantics (exact), so the generated test enforces
    # it rather than passing on the first matching exchange.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { path: /api/items, count: 2 }\n"
    )
    assert "expect(exchanges.filter(e =>" in code
    assert ".length).toBe(2);" in code


def test_request_assertion_url_and_url_matches() -> None:
    exact = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { url: 'https://api.test/v1/items' }\n"
    )
    assert "e.url === 'https://api.test/v1/items'" in exact
    regex = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { urlMatches: '/items/[0-9]+' }\n"
    )
    assert "/\\/items\\/[0-9]+/.test(e.url)" in regex


def test_request_assertion_path_matches_is_regexp_over_pathname() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { pathMatches: '^/api/' }\n"
    )
    assert "/^\\/api\\//.test(new URL(e.url).pathname)" in code


def test_request_assertion_body_matches_guards_against_missing_body() -> None:
    # bodyMatches is a regex over the *request* body; the runner fails when the body is missing
    # (match_request returns False for ex.request_body is None), so the predicate guards
    # `e.body !== null` before testing — otherwise a pattern like `.*` would match a body-less
    # request and pass incorrectly.
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - request: { path: /api/login, bodyMatches: 'token' }\n"
    )
    assert "e.body !== null && /token/.test(e.body)" in code


def test_wait_until_request_polls_recorded_exchanges_to_timeout() -> None:
    # until:{request} is satisfied if a matching exchange was already observed, otherwise it waits;
    # expect.poll over the growing recorder captures both (an already-seen exchange passes at once).
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/items, status: 200 } }, timeout: 4 }\n"
    )
    assert "await expect.poll(() => exchanges.filter(e =>" in code
    assert "{ timeout: 4000 }" in code
    assert ".toBeGreaterThanOrEqual(1)" in code
    assert "waitForResponse" not in code and "waitForRequest" not in code


def test_wait_until_request_with_count_is_a_lower_bound() -> None:
    # For an `until` wait, `count` is a lower bound (the runner keeps polling until it is reached).
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/items, count: 3 } }, timeout: 2 }\n"
    )
    assert ".toBeGreaterThanOrEqual(3)" in code


def test_request_sequence_checks_order_over_recorded_exchanges() -> None:
    # The sequence check is about order over the observed exchanges — a forward scan mirroring the
    # runtime, not sequential future-only waits (which would impose a different ordering constraint).
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - requestSequence:\n"
        "        - { path: /api/a }\n"
        "        - { path: /api/b, status: 200 }\n"
    )
    assert "// requestSequence /api/a → /api/b status=200" in code
    assert "const seq = [" in code
    assert "for (const e of exchanges) if (i < seq.length && seq[i](e)) i++;" in code
    assert "expect(i).toBe(seq.length);" in code
    assert code.index("/api/a") < code.index("/api/b")
    assert "waitForResponse" not in code and "waitForRequest" not in code


def test_response_schema_is_labeled_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n  expect:\n"
        "    - responseSchema: { request: { path: /api/items }, schema: items.json }\n"
    )
    assert "// TODO: responseSchema assertion (/api/items ~ items.json)" in code
    assert "JSON Schema" in code


def test_permissions_field_emits_a_labeled_todo_per_service() -> None:
    # No browser equivalent of an OS permission model (BE-0276), so it stays a TODO here too.
    code = _gen(
        "- name: x\n  permissions: { camera: grant, location: revoke }\n  steps:\n"
        "    - tap: { id: a }\n"
    )
    assert "// TODO: permissions.camera (grant)" in code
    assert "// TODO: permissions.location (revoke)" in code


def test_unsupported_selector_todo_names_field_and_reason() -> None:
    with_within = _gen("- name: x\n  steps:\n    - tap: { id: c, within: { id: parent } }\n")
    assert "// TODO: unsupported selector ('within':" in with_within
    with_value = _gen("- name: x\n  steps:\n    - tap: { id: f, value: '5' }\n")
    assert "// TODO: unsupported selector ('value':" in with_value
    interior_glob = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'a*b*c' }\n")
    assert "// TODO: unsupported selector ('idMatches':" in interior_glob


def test_string_escaping() -> None:
    code = _gen('- name: x\n  steps:\n    - type: { text: "it\'s", into: { id: f } }\n')
    assert r"await page.getByTestId('f').fill('it\'s');" in code


def test_describe_name_for_humanizes_stem() -> None:
    assert describe_name_for("components") == "Components"
    assert describe_name_for("long_press-flow") == "Long Press Flow"
    assert describe_name_for("") == "Generated"


def _cli_setup(tmp_path: Path) -> tuple[Path, Path]:
    """A config with one web app (baseUrl) and one iOS app (bundleId), plus a scenario file."""
    cfg = tmp_path / "bajutsu.config.yaml"
    cfg.write_text(
        "targets:\n"
        "  web: { baseUrl: 'http://localhost:3000', idNamespaces: [home] }\n"
        "  ios: { bundleId: com.example.ios, idNamespaces: [home] }\n",
        encoding="utf-8",
    )
    scn = tmp_path / "s.yaml"
    scn.write_text("- name: demo\n  steps:\n    - tap: { id: home.title }\n", encoding="utf-8")
    return cfg, scn


def test_cli_emit_playwright_writes_spec(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    out = tmp_path / "demo.spec.ts"
    r = runner.invoke(
        app,
        [
            "codegen",
            str(scn),
            "--target",
            "web",
            "--emit",
            "playwright",
            "-o",
            str(out),
            "--config",
            str(cfg),
        ],
    )
    assert r.exit_code == 0, r.output
    code = out.read_text(encoding="utf-8")
    assert "const BASE_URL = 'http://localhost:3000';" in code
    assert "await page.getByTestId('home.title').click();" in code


def test_cli_emit_playwright_without_base_url_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "ios", "--emit", "playwright", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "baseUrl" in r.output


def test_cli_unsupported_emit_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "web", "--emit", "bogus", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "unsupported --emit" in r.output


def test_manual_step_is_a_labeled_todo() -> None:
    code = _gen('- name: x\n  steps:\n    - manual: { label: "solve the CAPTCHA" }\n')
    assert "// TODO: manual step — solve the CAPTCHA" in code
    assert "no deterministic run-time equivalent" in code


def test_handle_system_alert_is_todo() -> None:
    # BE-0316 is an iOS SpringBoard concept; the web has no OS-level prompt, so codegen emits a
    # labeled TODO rather than the catch-all "unsupported step".
    code = _gen(
        "- name: x\n  steps:\n    - handleSystemAlert: { sel: { label: Allow }, timeout: 5 }\n"
    )
    assert "// TODO: handleSystemAlert" in code
    assert "iOS-only" in code
    assert "unsupported step" not in code
