"""Tests for UI Automator code generation (structural scenario -> Kotlin)."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from bajutsu.cli import app
from bajutsu.codegen import EMIT_TARGETS, CodegenError, generate_test
from bajutsu.codegen.uiautomator import class_name_for, to_uiautomator
from bajutsu.config import load_config, resolve
from bajutsu.scenario import load_scenarios

PACKAGE = "com.example.app"
runner = CliRunner()


def _gen(yaml: str, env: dict[str, str] | None = None, package: str = PACKAGE) -> str:
    scenarios = load_scenarios(yaml)
    return to_uiautomator(scenarios, "ComponentsUITest", package, env or {})


def test_header_class_package_and_runner() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "// Generated by bajutsu" in code
    assert "import androidx.test.uiautomator.By" in code
    assert "@RunWith(AndroidJUnit4::class)" in code
    assert "class ComponentsUITest {" in code
    assert f'private const val PACKAGE = "{PACKAGE}"' in code


def test_test_per_scenario_uses_sanitized_name_and_launch() -> None:
    code = _gen("- name: open the filter sheet\n  steps:\n    - tap: { id: a }\n")
    assert "@Test" in code
    assert "fun test_open_the_filter_sheet() {" in code
    assert "launch(extras)" in code


def test_launch_env_merges_config_and_scenario_as_intent_extras() -> None:
    code = _gen(
        "- name: x\n  preconditions:\n    launchEnv: { SHOWCASE_TAB: log }\n"
        "  steps:\n    - tap: { id: a }\n",
        env={"SHOWCASE_UITEST": "1"},
    )
    assert "val extras = mutableMapOf<String, String>()" in code
    assert 'extras["SHOWCASE_UITEST"] = "1"' in code
    assert 'extras["SHOWCASE_TAB"] = "log"' in code


def test_act_preamble_is_emitted() -> None:
    # Every act(...) call site depends on this preamble compiling — a dropped or broken helper
    # would leave the call sites' string assertions passing while the generated Kotlin fails to
    # build (undefined `act`, missing `UiObject2` import).
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "import androidx.test.uiautomator.BySelector" in code
    assert "import androidx.test.uiautomator.UiObject2" in code
    assert "private const val ACT_TIMEOUT_MS" in code
    assert "private fun act(by: BySelector): UiObject2 {" in code


def test_launch_checks_its_window_wait_and_re_issues_the_intent() -> None:
    # The window wait used to be issued and its result dropped, so a launch whose window never
    # reached the accessibility tree fell through and failed later at the first act() — 15s of
    # "no element matched" pointing at the selector instead of at the launch. Check the result,
    # and re-launch rather than widen the wait: a window the read channel never reports is not a
    # slow first frame, so waiting longer on the same launch cannot recover it.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "private const val LAUNCH_TIMEOUT_MS" in code
    assert "private const val LAUNCH_ATTEMPTS" in code
    assert "for (attempt in 1..LAUNCH_ATTEMPTS) {" in code
    assert "if (device.wait(Until.hasObject(by), LAUNCH_TIMEOUT_MS)) {" in code
    assert (
        '"launch: no $PACKAGE window in the accessibility tree after $LAUNCH_ATTEMPTS attempt(s) "'
    ) in code


def test_launch_waits_for_the_window_then_for_it_to_settle() -> None:
    # The window wait alone only proves some window from the package exists, not that its first
    # frame has finished drawing — waitForIdle closes that gap before act()'s own wait starts.
    # It sits on the success path: running it after a wait that found no window settles nothing.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    lines = [line.strip() for line in code.splitlines()]
    window_idx = lines.index("if (device.wait(Until.hasObject(by), LAUNCH_TIMEOUT_MS)) {")
    idle_idx = lines.index("device.waitForIdle(LAUNCH_TIMEOUT_MS)")
    assert window_idx < idle_idx < lines.index("return", idle_idx)


def test_a_slow_cold_start_is_waited_out_rather_than_restarted() -> None:
    # Every attempt waits the full LAUNCH_TIMEOUT_MS. A shorter per-attempt wait would relaunch a
    # cold start that was merely still on its way, and FLAG_ACTIVITY_CLEAR_TASK tears the activity
    # down — so each retry would send a slow app back to the beginning and could starve it, where a
    # single long wait would have succeeded. Only a window absent for the whole timeout is stuck
    # rather than slow.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    # No second, shorter budget: the attempt wait and the ceiling are the same constant.
    assert "LAUNCH_ATTEMPT_TIMEOUT_MS" not in code
    assert code.count("LAUNCH_TIMEOUT_MS") >= 3
    # The intent is rebuilt per attempt, so a relaunch re-delivers launchEnv through onCreate;
    # resuming the existing task instead would route the extras to onNewIntent.
    launch = code[code.index("private fun launch") :]
    body = launch[: launch.index("private fun act")]
    assert body.index("for (attempt in 1..LAUNCH_ATTEMPTS)") < body.index(
        "getLaunchIntentForPackage"
    )


def _fn_body(code: str, name: str, next_name: str) -> str:
    """The emitted body of one generated Kotlin function, so an assertion on ordering inside it
    cannot be satisfied by a matching line that lives in some other function."""
    start = code.index(f"private fun {name}")
    return code[start : code.index(f"private fun {next_name}", start)]


def test_launch_confirms_window_tracking_before_it_waits_on_the_tree() -> None:
    # The launch wait can only see the app through the accessibility window list, so a list that is
    # never reported reads exactly like an app that never started. CI run 30899952762 failed all
    # three attempts that way: 153, 168, and 171 polls over 20s with the activity RESUMED and
    # Displayed, and no window enumerated once. Check the channel first, so the failure names it.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    body = _fn_body(code, "launch", "act")
    # Inside the attempt loop and before the intent: a check that ran after startActivity would
    # kick the app it just launched back to the launcher.
    assert (
        body.index("for (attempt in 1..LAUNCH_ATTEMPTS)")
        < body.index("ensureWindowTracking()")
        < body.index("context.startActivity(intent)")
    )


def test_a_wedged_window_list_is_kicked_rather_than_waited_out() -> None:
    # The list is delivered by event, so no timeout can recover one that is never sent — only a
    # window change can. Raising the timeout was measured not to help (5s -> 15s -> 20s across
    # several runs), so assert the recovery itself: read, kick, and only then fail.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "private const val TRACKING_KICK_ATTEMPTS" in code
    body = _fn_body(code, "ensureWindowTracking", "launch")
    # Bounded, and the kick is reached from inside the loop — a bounded loop that only re-read the
    # same list would satisfy a mere "is the helper defined" assertion while recovering nothing.
    assert (
        body.index("for (attempt in 1..TRACKING_KICK_ATTEMPTS)")
        < body.index("kickWindowTracking(")
        < body.index("throw AssertionError(")
    )
    # A kick that never lands fails here, naming the channel — not 15s later at a selector.
    assert "accessibility window tracking reported no windows after" in body
    # The read cannot throw past that AssertionError: getWindows() raises IllegalStateException
    # when the connection is not established, which is the fault being reported.
    assert "private fun reportsWindows(): Boolean = runCatching {" in code

    kick = _fn_body(code, "kickWindowTracking", "reportsWindows")
    assert "device.pressHome()" in kick
    # pressHome reports a missing window event by returning false, and no event is the wedge's own
    # symptom — a dropped return would discard the single most diagnostic outcome.
    assert "if (!device.pressHome())" in kick
    # Nesting is banned across the whole emitted file, not just in this helper, and that breadth is
    # deliberate: pressHome, click, and swipe each wait through UiAutomation.executeAndWaitForEvent
    # internally, so wrapping any of them clears the queue the outer wait watches and leaves that
    # wait able only to time out. Scoping the check to kickWindowTracking would let the identical
    # bug land in the next helper. A future emitter with a genuine use for the call has to come
    # here, read this, and decide deliberately.
    #
    # Comment lines are stripped so rewording a rationale cannot redden the gate on its own.
    emitted = "\n".join(ln for ln in code.splitlines() if not ln.lstrip().startswith("//"))
    assert "executeAndWaitForEvent" not in emitted


def test_a_timed_out_launch_attempt_kicks_only_while_an_attempt_remains() -> None:
    # A stale-but-non-empty list satisfies ensureWindowTracking() while still being one the app's
    # window never joined, and no is-it-empty check tells those apart, so a failed attempt kicks
    # regardless. But not after the last one: HOME would leave the AssertionError's own window
    # summary, the hierarchy dump, and the screenshot all describing the launcher — and a healthy
    # launcher window list argues the opposite of the failure they were collected to explain.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    body = _fn_body(code, "launch", "act")
    assert (
        body.index('Log.w(LOG_TAG, "launch attempt $attempt saw no')
        < body.index("if (attempt < LAUNCH_ATTEMPTS) {")
        < body.index('kickWindowTracking("launch attempt $attempt timed out")')
    )
    # The per-attempt log carries the window list, not only the miss. An empty list and a stale
    # non-empty one both reach here and call for different fixes, and the AssertionError raised
    # after the loop reports only the state left behind once every attempt has run.
    #
    # Sliced to that one statement rather than searched for in the whole body, because the trailing
    # AssertionError appends windowSummary() too — a body-wide search would pass with the
    # per-attempt summary dropped. The slice pins no line wrap or continuation indent, so reflowing
    # the emitted string cannot redden this on its own.
    per_attempt = body[
        body.index('Log.w(LOG_TAG, "launch attempt $attempt saw no') : body.index(
            "if (attempt < LAUNCH_ATTEMPTS) {"
        )
    ]
    assert "windowSummary()" in per_attempt


def test_failure_messages_name_the_windows_that_were_searched() -> None:
    # "no element matched <selector>" cannot distinguish an id that has not rendered from an app
    # whose window is absent from the accessibility tree altogether — the two need opposite fixes.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "InstrumentationRegistry.getInstrumentation().uiAutomation.windows" in code
    assert 'root=${window.root?.packageName ?: "<null>"} $window' in code
    assert 'within ${ACT_TIMEOUT_MS}ms; windows:\\n" + windowSummary()' in code


def test_failure_dumps_hierarchy_screenshot_and_windows_as_artifacts() -> None:
    # On failure the generated test writes the state it read the assertion from into the directory
    # the Android Gradle Plugin names with `additionalTestOutputDir` and copies off the device after
    # the run, which CI uploads (android-e2e.yml). Not the app's own external files directory: `adb`
    # cannot read /sdcard/Android/data/<package> from Android 11 on, so a dump written there is
    # stranded on the device.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert 'private const val DIAGNOSTICS_DIR = "codegen-diagnostics"' in code
    assert 'private const val ADDITIONAL_OUTPUT_ARG = "additionalTestOutputDir"' in code
    assert "InstrumentationRegistry.getArguments().getString(ADDITIONAL_OUTPUT_ARG)" in code
    assert "@get:Rule" in code
    assert "val diagnostics: TestRule = object : TestWatcher() {" in code
    assert "override fun failed(error: Throwable, description: Description) {" in code
    # A platform-typed methodName would make Kotlin insert an invisible null check, losing
    # the evidence to a NullPointerException on the one path that needs it.
    assert "dumpDiagnostics(description.methodName ?: description.displayName)" in code
    assert (
        'it.writeText("accessibility windows:\\n$summary\\n\\nmatchable ids:\\n${matchableIds()}\\n")'
    ) in code
    assert 'dump(File(dir, "$stem-hierarchy.xml")) { device.dumpWindowHierarchy(it) }' in code
    assert 'dump(File(dir, "$stem-screen.png")) {' in code
    for line in ("import org.junit.Rule", "import org.junit.rules.TestRule"):
        assert line in code
    for line in ("import org.junit.rules.TestWatcher", "import org.junit.runner.Description"):
        assert line in code
    assert "import java.io.File" in code
    assert "import android.util.Log" in code


def test_failure_records_the_ids_the_selector_was_matched_against() -> None:
    # `dumpWindowHierarchy` reports `resource-id` from the raw node, which leaves a Compose testTag
    # surfaced by testTagsAsResourceId blank — so the hierarchy alone cannot answer "was this id
    # matchable?". Reading the ids back through `By.res` uses the matcher a selector goes through.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert 'device.findObjects(By.res(Pattern.compile(".+")))' in code
    assert ".mapNotNull { it.resourceName }.distinct().sorted()" in code


def test_each_dump_is_written_independently_and_reports_its_own_failure() -> None:
    # A hierarchy dump that throws must not cost the screenshot, nor the window list that names the
    # windows the failing wait searched — each is separate evidence for a different failure mode.
    # Nor may the throw pass silently: an artifact that is simply absent explains nothing on the one
    # path meant to explain a failure, so the file and the reason go to logcat.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "private fun dump(file: File, write: (File) -> Unit) {" in code
    assert (
        'runCatching { write(file) }.onFailure { Log.w(LOG_TAG, "could not write $file", it) }'
    ) in code
    body = code[code.index("private fun dumpDiagnostics") : code.index("private fun diagnostics")]
    assert body.count("dump(File(dir, ") == 3
    # takeScreenshot reports failure by returning false, which `dump` would otherwise never see.
    assert 'if (!device.takeScreenshot(it)) error("takeScreenshot returned false")' in code


def test_no_usable_directory_is_reported_rather_than_written_to_a_relative_path() -> None:
    # `File(parent, DIAGNOSTICS_DIR)` with a null parent is a *relative* path, so the dumps would
    # land somewhere the harness never collects — silently losing the evidence they exist for. A
    # blank `additionalTestOutputDir` counts as absent for the same reason: `File("")` resolves to
    # the current directory rather than to the collected one.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    assert "if (!collected.isNullOrBlank()) return File(collected)" in code
    assert "val parent = diagnosticsParent()" in code
    assert "if (parent == null) {" in code
    assert '"no directory to write evidence to; see the window list above"' in code
    assert "val dir = File(parent, DIAGNOSTICS_DIR)" in code


def test_the_diagnostic_helpers_cannot_throw_over_the_failure_they_explain() -> None:
    # `windowSummary()` is concatenated into the AssertionError that `launch` / `act` raise, and
    # `matchableIds()` into the `<test>-windows.txt` dump. A throw in either would replace the
    # failure's own message or cost that evidence, so each resolves to a placeholder instead.
    code = _gen("- name: x\n  steps:\n    - tap: { id: a }\n")
    for helper in ("windowSummary", "matchableIds"):
        assert f"private fun {helper}(): String = runCatching {{" in code
    assert code.count('}.getOrElse { "<unavailable: $it>" }') == 2


def test_tap_by_id_text_and_desc() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - tap: { id: onboarding.start }\n"
        "    - tap: { label: Submit }\n"
        "    - tap: { value: off }\n"
    )
    assert 'act(byId("onboarding.start")).click()' in code
    assert 'act(By.text("Submit")).click()' in code
    assert 'act(By.desc("off")).click()' in code


def test_type_into_sets_text_and_bare_type_is_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - type: { text: a@b.com, into: { id: auth.email } }\n"
        "    - type: { text: hello }\n"
    )
    assert 'act(byId("auth.email")).text = "a@b.com"' in code
    assert "// TODO: type without a target" in code


def test_text_editing_steps_emit_uiautomator_peers() -> None:
    # BE-0265: clear -> UiObject2.clear(), delete -> focus + N KEYCODE_DEL, select -> Ctrl+A,
    # copy -> Ctrl+C. The KeyEvent import backs the key codes.
    code = _gen(
        "- name: x\n  steps:\n"
        "    - clear: { into: { id: form.note } }\n"
        "    - delete: { into: { id: form.note }, count: 2 }\n"
        "    - select: { into: { id: form.note } }\n"
        "    - copy: {}\n"
    )
    assert "import android.view.KeyEvent" in code
    assert 'act(byId("form.note")).clear()' in code
    assert "repeat(2) { device.pressKeyCode(KeyEvent.KEYCODE_DEL) }" in code
    assert "device.pressKeyCode(KeyEvent.KEYCODE_A, KeyEvent.META_CTRL_ON)" in code
    assert "device.pressKeyCode(KeyEvent.KEYCODE_C, KeyEvent.META_CTRL_ON)" in code


def test_back_presses_the_system_key() -> None:
    # BE-0210: UI Automator has a native system back (peer of the adb driver's keyevent 4).
    code = _gen("- name: x\n  steps:\n    - back: {}\n")
    assert "device.pressBack()" in code
    assert "TODO" not in code


def test_wait_for_and_until_gone() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { for: { id: home.title }, timeout: 5 }\n"
        "    - wait: { until: { gone: { id: spinner } }, timeout: 3 }\n"
    )
    assert 'assertTrue(device.wait(Until.hasObject(byId("home.title")), 5000L))' in code
    assert 'assertTrue(device.wait(Until.gone(byId("spinner")), 3000L))' in code


def test_swipe_direction_and_from_to_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - swipe: { on: { id: list }, direction: up }\n"
        "    - swipe: { from: [0.5, 0.8], to: [0.5, 0.2] }\n"
    )
    assert 'act(byId("list")).swipe(Direction.UP, 0.75f)' in code
    assert "// TODO: coordinate swipe (from/to) is not generated" in code


def test_drag_maps_to_swipe_gesture() -> None:
    # `drag` (BE-0227) is an element-anchored pointer drag; UiObject2.swipe is a real drag, so it
    # emits the same primitive a directional swipe does.
    code = _gen("- name: x\n  steps:\n    - drag: { on: { id: divider }, direction: right }\n")
    assert 'act(byId("divider")).swipe(Direction.RIGHT, 0.75f)' in code


def test_scroll_maps_to_uiscrollable_scroll_into_view() -> None:
    # UI Automator has a native scroll-to-element: UiScrollable.scrollIntoView, bounded by
    # setMaxSearchSwipes (the peer of maxScrolls) — `scroll` (BE-0326) emits it for id / label targets.
    code = _gen(
        "- name: x\n  steps:\n    - scroll: { to: { id: notice.row.20 }, maxScrolls: 25 }\n"
    )
    assert (
        "UiScrollable(UiSelector().scrollable(true)).setAsVerticalList()"
        '.setMaxSearchSwipes(25).scrollIntoView(UiSelector().resourceIdMatches("(.*:id/)?" '
        '+ Pattern.quote("notice.row.20")))'
    ) in code


def test_scroll_with_a_compound_selector_is_a_todo() -> None:
    # scrollIntoView takes a UiSelector, which maps only the primary id / label forms; a compound
    # selector has no faithful single UiSelector, so it stays a labeled TODO (BE-0326).
    code = _gen("- name: x\n  steps:\n    - scroll: { to: { id: a, value: v } }\n")
    assert "// TODO: unsupported selector" in code


def test_long_press_pinch_and_unsupported_gestures() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - longPress: { sel: { id: comp.longpress }, duration: 0.6 }\n"
        "    - pinch: { sel: { id: photo }, scale: 2.0 }\n"
        "    - pinch: { sel: { id: photo }, scale: 0.5 }\n"
        "    - doubleTap: { id: comp.double }\n"
        "    - rotate: { sel: { id: photo }, radians: 1.5 }\n"
    )
    assert 'act(byId("comp.longpress")).longClick()' in code
    assert 'act(byId("photo")).pinchOpen(0.5f)' in code
    assert 'act(byId("photo")).pinchClose(0.5f)' in code
    assert "// TODO: doubleTap" in code
    assert "// TODO: rotate" in code


def test_relaunch_relaunches_with_extras() -> None:
    code = _gen("- name: x\n  steps:\n    - relaunch: {}\n")
    # `launch(extras)` appears once for the initial launch and once for the relaunch step.
    assert code.count("launch(extras)") == 2


def test_assertions_exist_label_value_state_and_count() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n"
        "  expect:\n"
        "    - exists: { id: home.title }\n"
        "    - exists: { id: spinner, negate: true }\n"
        "    - label: { sel: { id: greeting }, equals: Hello }\n"
        "    - label: { sel: { id: greeting }, contains: ell }\n"
        "    - value: { sel: { id: toggle }, equals: off }\n"
        "    - enabled: { id: submit }\n"
        "    - disabled: { id: cancel }\n"
        "    - selected: { id: tab.home }\n"
        "    - count: { sel: { id: row }, equals: 3 }\n"
        "    - count: { sel: { id: row }, atLeast: 1 }\n"
    )
    assert 'assertTrue(device.hasObject(byId("home.title")))' in code
    assert 'assertFalse(device.hasObject(byId("spinner")))' in code
    assert 'assertEquals("Hello", device.findObject(byId("greeting")).text)' in code
    assert 'assertTrue(device.findObject(byId("greeting")).text.contains("ell"))' in code
    assert 'assertEquals("off", device.findObject(byId("toggle")).contentDescription)' in code
    assert 'assertTrue(device.findObject(byId("submit")).isEnabled)' in code
    assert 'assertFalse(device.findObject(byId("cancel")).isEnabled)' in code
    assert 'assertTrue(device.findObject(byId("tab.home")).isSelected)' in code
    assert 'assertEquals(3, device.findObjects(byId("row")).size)' in code
    assert 'assertTrue(device.findObjects(byId("row")).size >= 1)' in code


def test_id_matches_glob_maps_to_res_pattern() -> None:
    # An fnmatch glob is a whole-string match, so By.res(Pattern) (Matcher.matches()) is faithful.
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row.*' }\n")
    assert 'By.res(Pattern.compile("(.*:id/)?row\\\\..*"))' in code


def test_id_candidate_list_emits_byanyid() -> None:
    # A cross-platform selector (BE-0221) targets either Android toolkit: uiautomator can't tell
    # whether the build surfaces the dotted (Compose) or underscore (Views) id, so it matches ANY
    # candidate via byAnyId rather than picking the first — otherwise a Views target never resolves.
    code = _gen("- name: x\n  steps:\n    - tap: { id: [stable.refresh, stable_refresh] }\n")
    assert 'act(byAnyId("stable.refresh", "stable_refresh")).click()' in code
    # The byAnyId helper is defined in the generated preamble.
    assert "private fun byAnyId(vararg ids: String)" in code


def test_id_matches_candidate_list_alternates_res_patterns() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: ['stable.row.*', 'stable_row_*'] }\n")
    assert (
        'By.res(Pattern.compile("(?:(.*:id/)?stable\\\\.row\\\\..*)|(?:(.*:id/)?stable_row_.*)"))'
        in code
    )


def test_id_matches_candidate_list_with_class_char_is_todo() -> None:
    # A `[...]` class in *any* candidate has no faithful regex (fnmatch-vs-regex negation differs),
    # so the whole selector conservatively degrades to a TODO — it must not emit a partial/wrong
    # alternation from only the clean candidates (BE-0221).
    code = _gen(
        "- name: x\n  steps:\n    - tap: { idMatches: ['stable.row[0-9]', 'stable_row_*'] }\n"
    )
    assert "// TODO: unsupported selector" in code
    assert (
        "(?:" not in code
    )  # no partial alternation emitted (only the byId/byAnyId preamble helpers)


def test_label_matches_substring_maps_to_contains_but_regex_is_todo() -> None:
    # `By.text(Pattern)` is a full-string match, unlike labelMatches' re.search — so a plain
    # substring maps to By.textContains, while a real regex (e.g. `^Item `) has no faithful form.
    substr = _gen("- name: x\n  steps:\n    - tap: { labelMatches: 'Item' }\n")
    assert 'act(By.textContains("Item")).click()' in substr
    regex = _gen("- name: x\n  steps:\n    - tap: { labelMatches: '^Item ' }\n")
    assert "// TODO: unsupported selector" in regex


def test_compound_selector_is_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: row, index: 2 }\n    - tap: { traits: [button] }\n"
    )
    assert code.count("// TODO: unsupported selector") == 2


def test_network_and_device_control_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - setLocation: { lat: 1.0, lon: 2.0 }\n"
        "  expect:\n    - request: { path: /api/x }\n"
    )
    assert "// TODO: setLocation" in code
    assert "// TODO: request assertion" in code


def test_permissions_field_emits_a_labeled_todo_per_service() -> None:
    code = _gen(
        "- name: x\n  permissions: { camera: grant, notifications: grant }\n  steps:\n"
        "    - tap: { id: a }\n"
    )
    assert "// TODO: permissions.camera (grant)" in code
    assert "// TODO: permissions.notifications (grant)" in code


def test_text_and_value_regex_and_contains() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - tap: { id: a }\n"
        "  expect:\n"
        "    - label: { sel: { id: greeting }, matches: '^Hello' }\n"
        "    - value: { sel: { id: toggle }, contains: of }\n"
        "    - count: { sel: { id: row }, atMost: 5 }\n"
    )
    assert 'assertTrue(device.findObject(byId("greeting")).text.contains(Regex("^Hello")))' in code
    assert 'assertTrue(device.findObject(byId("toggle")).contentDescription.contains("of"))' in code
    assert 'assertTrue(device.findObjects(byId("row")).size <= 5)' in code


def test_wait_until_request_and_settle_and_request_sequence_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { request: { path: /api/x } }, timeout: 5 }\n"
        "    - wait: { until: settled, timeout: 2 }\n"
        "  expect:\n"
        "    - requestSequence:\n        - { path: /a }\n        - { path: /b }\n"
    )
    assert "// TODO: wait until request" in code
    # `findObject` does not auto-wait, so a settle maps to `waitForIdle`, not a bare comment.
    assert "device.waitForIdle(2000L)" in code
    assert "// TODO: requestSequence assertion" in code


def test_device_control_and_helper_steps_are_labeled_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - push: { payload: {} }\n"
        "    - setClipboard: { text: hi }\n"
        "    - totp: { secret: GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ, into: { var: code } }\n"
        "    - email: { match: { subjectMatches: Verify }, extract: { var: pin, "
        "bodyMatches: 'PIN (\\d+)' }, timeout: 10 }\n"
        "    - background: {}\n"
    )
    assert "// TODO: push" in code
    assert "// TODO: setClipboard(text: " in code
    assert "// TODO: totp(into: code)" in code
    assert "// TODO: email(into: pin)" in code
    assert "// TODO: unsupported step" in code


def test_response_schema_and_visual_assertions_are_todo() -> None:
    code = _gen(
        "- name: x\n  steps:\n    - assert:\n"
        "        - responseSchema: { request: { path: /api/items }, schema: items.json }\n"
        "        - visual: { baseline: home.png }\n"
    )
    assert "// TODO: responseSchema assertion (/api/items)" in code
    assert "// TODO: unsupported assertion" in code


def test_compound_selector_in_wait_and_assertion_is_unsupported() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { for: { id: row, index: 0 }, timeout: 2 }\n"
        "  expect:\n    - label: { sel: { traits: [button] }, equals: OK }\n"
    )
    assert code.count("// TODO: unsupported selector") == 2


def test_compound_selector_in_gone_count_state_is_unsupported() -> None:
    code = _gen(
        "- name: x\n  steps:\n"
        "    - wait: { until: { gone: { id: row, index: 0 } }, timeout: 2 }\n"
        "  expect:\n"
        "    - exists: { traits: [button] }\n"
        "    - count: { sel: { traits: [button] }, equals: 1 }\n"
        "    - enabled: { id: submit, index: 0 }\n"
    )
    assert code.count("// TODO: unsupported selector") == 4


def test_id_matches_char_class_is_unsupported() -> None:
    code = _gen("- name: x\n  steps:\n    - tap: { idMatches: 'row[0-9]' }\n")
    assert "// TODO: unsupported selector" in code


def test_string_literals_escape_kotlin_specials() -> None:
    # Kotlin forbids a raw line break in a "…" literal and reads `$` as a template start, so both
    # must be escaped or the generated file would not compile.
    code = _gen('- name: x\n  steps:\n    - type: { text: "a$b\\nc", into: { id: f } }\n')
    assert r'act(byId("f")).text = "a\$b\nc"' in code


def test_class_name_for_stem() -> None:
    assert class_name_for("login_flow") == "LoginFlowUITest"
    assert class_name_for("!!!") == "GeneratedUITest"
    # A digit-leading stem must not produce an identifier that starts with a digit — that is not a
    # valid Kotlin class name and would fail to compile.
    assert class_name_for("2fa_flow") == "_2FaFlowUITest"


def test_scenario_name_sanitizing_edges() -> None:
    assert "fun test_scenario()" in _gen("- name: '!!!'\n  steps:\n    - tap: { id: a }\n")
    assert "fun test__2fa()" in _gen("- name: '2fa'\n  steps:\n    - tap: { id: a }\n")


def test_uiautomator_is_a_registered_emit_target() -> None:
    assert "uiautomator" in EMIT_TARGETS


def test_generate_test_on_android_target_returns_kt_file() -> None:
    eff = resolve(load_config("targets:\n  droid:\n    package: com.example.app\n"), "droid")
    code, filename = generate_test(
        "uiautomator", load_scenarios("- name: x\n  steps:\n    - tap: { id: a }\n"), "login", eff
    )
    assert filename == "LoginUITest.kt"
    assert "class LoginUITest {" in code


def test_generate_test_uiautomator_on_non_android_target_fails() -> None:
    eff = resolve(load_config("targets:\n  web:\n    baseUrl: http://localhost:3000\n"), "web")
    with pytest.raises(CodegenError, match="Android target"):
        generate_test(
            "uiautomator", load_scenarios("- name: x\n  steps:\n    - tap: { id: a }\n"), "x", eff
        )


def _cli_setup(tmp_path: Path) -> tuple[Path, Path]:
    """A config with one Android app (package) and one web app (baseUrl), plus a scenario file."""
    cfg = tmp_path / "bajutsu.config.yaml"
    cfg.write_text(
        "targets:\n"
        "  droid: { package: com.example.app, idNamespaces: [home] }\n"
        "  web: { baseUrl: 'http://localhost:3000', idNamespaces: [home] }\n",
        encoding="utf-8",
    )
    scn = tmp_path / "s.yaml"
    scn.write_text("- name: demo\n  steps:\n    - tap: { id: home.title }\n", encoding="utf-8")
    return cfg, scn


def test_cli_emit_uiautomator_writes_kt(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    out = tmp_path / "Demo.kt"
    r = runner.invoke(
        app,
        [
            "codegen",
            str(scn),
            "--target",
            "droid",
            "--emit",
            "uiautomator",
            "-o",
            str(out),
            "--config",
            str(cfg),
        ],
    )
    assert r.exit_code == 0, r.output
    code = out.read_text(encoding="utf-8")
    assert 'private const val PACKAGE = "com.example.app"' in code
    assert 'act(byId("home.title")).click()' in code


def test_cli_emit_uiautomator_without_package_exits(tmp_path: Path) -> None:
    cfg, scn = _cli_setup(tmp_path)
    r = runner.invoke(
        app, ["codegen", str(scn), "--target", "web", "--emit", "uiautomator", "--config", str(cfg)]
    )
    assert r.exit_code == 2
    assert "package" in r.output


def test_manual_step_is_a_labeled_todo() -> None:
    code = _gen('- name: x\n  steps:\n    - manual: { label: "solve the CAPTCHA" }\n')
    assert "// TODO: manual step — solve the CAPTCHA" in code
    assert "no deterministic run-time equivalent" in code


def test_runtime_only_constructs_fail_loudly() -> None:
    # BE-0297: the fail-loudly guard lives in the shared walk (common.py), so `if` / `forEach` /
    # `extract` are rejected identically here as for XCUITest — never a silent no-op stub.
    with pytest.raises(CodegenError, match="`forEach` control-flow step"):
        _gen(
            "- name: x\n  steps:\n"
            "    - forEach:\n"
            "        sel: { idMatches: 'row.*' }\n"
            "        as: row\n"
            "        steps:\n"
            "          - tap: { id: '${vars.row}' }\n"
        )


# The checked-in UI Automator codegen fixture (BE-0294): the Android twin of the committed XCUITest
# fixture. The on-device `uiautomator (codegen)` CI job proves the generated Kotlin compiles and
# passes against a real emulator; these two fast-gate tests are its deterministic complement, catching
# a drifted fixture in `make check` without a Simulator — no LLM, no device.
_REPO_ROOT = Path(__file__).resolve().parent.parent
_FIXTURE_SCENARIO = _REPO_ROOT / "demos/showcase/scenarios/codegen_android.yaml"
_FIXTURE_KT = (
    _REPO_ROOT / "demos/showcase/android/compose/src/androidTest/java/CodegenAndroidUITest.kt"
)
_SHOWCASE_CONFIG = _REPO_ROOT / "demos/showcase/showcase.config.yaml"


def test_android_codegen_fixture_has_no_todo() -> None:
    # A `// TODO` marks a step the emitter could not translate faithfully; the generated test would
    # then compile but skip that step (or not compile at all). The fixture is scoped to the surface
    # that maps fully, so its checked-in .kt must carry none.
    assert "// TODO" not in _FIXTURE_KT.read_text(encoding="utf-8")


def test_android_codegen_fixture_is_up_to_date(tmp_path: Path) -> None:
    # Regenerate through the same CLI path `make -C demos/showcase/android e2e-codegen` uses (same
    # scenario, target, and `-o` stem) and compare byte-for-byte: an emitter or config change that
    # alters the generated Kotlin reddens the gate until the committed fixture is regenerated, so a
    # stale check-in can never silently diverge from what CI would build.
    out = tmp_path / _FIXTURE_KT.name
    result = runner.invoke(
        app,
        [
            "codegen",
            str(_FIXTURE_SCENARIO),
            "--emit",
            "uiautomator",
            "--target",
            "showcase-compose",
            "--config",
            str(_SHOWCASE_CONFIG),
            "-o",
            str(out),
        ],
    )
    assert result.exit_code == 0, result.output
    assert out.read_text(encoding="utf-8") == _FIXTURE_KT.read_text(encoding="utf-8")


def test_handle_system_alert_is_todo() -> None:
    # BE-0316 is iOS-only; Android reaches a system dialog with an ordinary tap, so codegen emits a
    # labeled TODO rather than the catch-all "unsupported step".
    code = _gen(
        "- name: x\n  steps:\n    - handleSystemAlert: { sel: { label: Allow }, timeout: 5 }\n"
    )
    assert "// TODO: handleSystemAlert" in code
    assert "iOS-only" in code
    assert "unsupported step" not in code
