// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import XCTest

final class ComponentsuitestsUITests: XCTestCase {
  private let app = XCUIApplication()
  private func el(_ id: String) -> XCUIElement {
    app.descendants(matching: .any)[id]
  }
  private func byLabel(_ label: String) -> XCUIElement {
    app.descendants(matching: .any).matching(NSPredicate(format: "label == %@", label)).firstMatch
  }
  private func matchingId(_ glob: String) -> XCUIElementQuery {
    app.descendants(matching: .any).matching(NSPredicate(format: "identifier LIKE %@", glob))
  }
  private func coord(_ x: CGFloat, _ y: CGFloat) -> XCUICoordinate {
    app.coordinate(withNormalizedOffset: CGVector(dx: 0, dy: 0)).withOffset(CGVector(dx: x, dy: y))
  }

  func test_filter_sheet_opens_then_closes() {
    app.launchEnvironment["SHOWCASE_UITEST"] = "1"
    app.launchEnvironment["SHOWCASE_TAB"] = "log"
    app.launch()

    el("log.openFilter").tap()
    XCTAssertTrue(el("log.sheet.title").waitForExistence(timeout: 5.0), "wait for element")
    el("log.sheet.apply").tap()
    XCTAssertTrue(el("log.sheet.title").waitForNonExistence(timeout: 5.0), "wait until gone")

    // expect
    XCTAssertFalse(el("log.sheet.title").exists)
  }

  func test_gallery_cover_opens_then_closes() {
    app.launchEnvironment["SHOWCASE_UITEST"] = "1"
    app.launchEnvironment["SHOWCASE_TAB"] = "log"
    app.launch()

    el("log.openGallery").tap()
    XCTAssertTrue(el("log.cover.title").waitForExistence(timeout: 5.0), "wait for element")
    el("log.cover.close").tap()
    XCTAssertTrue(el("log.cover.title").waitForNonExistence(timeout: 5.0), "wait until gone")

    // expect
    XCTAssertFalse(el("log.cover.title").exists)
  }

  func test_search_filters_the_catalog() {
    app.launchEnvironment["SHOWCASE_UITEST"] = "1"
    app.launchEnvironment["SHOWCASE_TAB"] = "search"
    app.launch()

    XCTAssertEqual(el("search.count").value as? String, "5")
    el("search.field").tap()
    el("search.field").typeText("Horse 5")
    XCTAssertTrue(el("search.row.5").waitForExistence(timeout: 5.0), "wait for element")

    // expect
    XCTAssertEqual(el("search.count").value as? String, "1")
    XCTAssertTrue(el("search.row.5").exists)
  }

}
