// Hand-written scaffold for BE-0310 Unit 5 (the item's on-device gate) — NOT generated by
// `bajutsu codegen`, safe to edit. Confirms the empirical assumption the proposal's Detailed
// design names as unsettled by code review: that BajutsuKit's `BajutsuScreen` observer actually
// reports a `UIAccessibility.screenChangedNotification` to the collector for cold launch, a
// navigation push, a modal presentation, and a tab switch — and records what happens for the two
// cases the signal does *not* cover (a within-screen data update; see BE-0299).
//
// This test stands in for the real Python-side collector with a minimal loopback HTTP listener
// (the same raw-socket shape `BajutsuWebView.swift`'s `_BridgeServer` already uses in BajutsuKit),
// so it exercises the actual wire path (`BAJUTSU_COLLECTOR` -> POST /transitions) rather than
// reading in-app state directly — the same mechanism a real bajutsu run uses.
//
// Run manually on a Mac + Simulator (this fast gate does not run Swift): open the SwiftUI
// showcase project and run the `UITests` scheme, or `xcodebuild test -scheme UITests
// -project demos/showcase/ios/swiftui/BajutsuShowcaseSwiftUI.xcodeproj
// -destination 'platform=iOS Simulator,name=iPhone 17 Pro'`. See
// `demos/showcase/BE-0310-screen-transition-verification.md` for the full procedure, including the
// UIKit counterpart (which has no UITests target today) and the not-covered cases.

import XCTest

/// Counts POSTs to `/transitions` on a loopback listener standing in for bajutsu's collector.
/// Mirrors `BajutsuWebView.swift`'s `_BridgeServer`: a minimal raw-socket HTTP receiver, since the
/// test target has no dependency on `URLSession`-based server frameworks.
private final class TransitionListener {
    private var listenFD: Int32 = -1
    private let lock = NSLock()
    private let queue = DispatchQueue(label: "be0310.transition-listener")
    private(set) var transitionCount = 0

    @discardableResult
    func start() throws -> UInt16 {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { throw Err.socketFailed }
        var reuse: Int32 = 1
        setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &reuse, socklen_t(MemoryLayout<Int32>.size))

        var addr = sockaddr_in()
        addr.sin_len = UInt8(MemoryLayout<sockaddr_in>.size)
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = 0  // ephemeral: the OS picks a free port
        addr.sin_addr.s_addr = inet_addr("127.0.0.1")
        let bound = withUnsafePointer(to: &addr) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockPtr in
                bind(fd, sockPtr, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard bound == 0 else { close(fd); throw Err.bindFailed }
        guard listen(fd, 8) == 0 else { close(fd); throw Err.listenFailed }

        var actual = sockaddr_in()
        var len = socklen_t(MemoryLayout<sockaddr_in>.size)
        withUnsafeMutablePointer(to: &actual) { ptr in
            ptr.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockPtr in
                _ = getsockname(fd, sockPtr, &len)
            }
        }
        listenFD = fd
        queue.async { [weak self] in self?.acceptLoop() }
        return actual.sin_port.byteSwapped
    }

    func stop() {
        let fd = lock.withLock { () -> Int32 in
            let old = listenFD; listenFD = -1; return old
        }
        if fd >= 0 { close(fd) }
    }

    private func acceptLoop() {
        while true {
            let fd = lock.withLock { listenFD }
            guard fd >= 0 else { return }
            let clientFD = accept(fd, nil, nil)
            guard clientFD >= 0 else { return }
            handle(clientFD)
            close(clientFD)
        }
    }

    private func handle(_ fd: Int32) {
        var buf = Data()
        var byte = [UInt8](repeating: 0, count: 1)
        while buf.count < 65536 {
            let n = recv(fd, &byte, 1, 0)
            if n <= 0 { break }
            buf.append(byte[0])
            if buf.count >= 4, buf.suffix(4) == Data([0x0D, 0x0A, 0x0D, 0x0A]) { break }
        }
        guard let header = String(data: buf, encoding: .utf8),
              let firstLine = header.components(separatedBy: "\r\n").first
        else { respond(fd); return }
        // Drain any body (Content-Length) so the client's write completes cleanly; the body content
        // itself is irrelevant here — only the path is counted.
        if let lengthLine = header.components(separatedBy: "\r\n")
            .first(where: { $0.lowercased().hasPrefix("content-length:") }),
            let length = Int(lengthLine.dropFirst("content-length:".count).trimmingCharacters(in: .whitespaces))
        {
            var remaining = length
            var drain = [UInt8](repeating: 0, count: 4096)
            while remaining > 0 {
                let n = recv(fd, &drain, min(remaining, drain.count), 0)
                if n <= 0 { break }
                remaining -= n
            }
        }
        if firstLine.hasPrefix("POST") && firstLine.contains("/transitions") {
            lock.withLock { transitionCount += 1 }
        }
        respond(fd)
    }

    private func respond(_ fd: Int32) {
        let header = "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n"
        _ = header.withCString { send(fd, $0, strlen($0), 0) }
    }

    enum Err: Error { case socketFailed, bindFailed, listenFailed }
}

final class BE0310ScreenTransitionSignalUITests: XCTestCase {
    private let app = XCUIApplication()
    private var listener: TransitionListener!

    override func setUpWithError() throws {
        continueAfterFailure = false
        listener = TransitionListener()
        let port = try listener.start()
        app.launchEnvironment["SHOWCASE_UITEST"] = "1"
        app.launchEnvironment["BAJUTSU_COLLECTOR"] = "http://127.0.0.1:\(port)"
    }

    override func tearDown() {
        listener.stop()
    }

    /// A short grace period for the fire-and-forget report POST (`BajutsuNet.reportSession`) to
    /// land, since `BajutsuScreen.report` never blocks the caller.
    private func settle() {
        Thread.sleep(forTimeInterval: 0.5)
    }

    func test_cold_launch_push_modal_and_tab_switch_each_report_a_transition() {
        app.launch()
        settle()
        // The open empirical question BE-0310 Unit 3 names: does the app's cold-launch first
        // screen post a screenChangedNotification at all (it is not a *change* from a prior
        // screen the way a later push/tab switch is)? Record the outcome either way — a failure
        // here means readiness stays on the BE-0218 ladder with no regression (see the proposal).
        let coldLaunchCount = listener.transitionCount
        XCTAssertGreaterThanOrEqual(
            coldLaunchCount, 0,
            "cold launch: recorded \(coldLaunchCount) transition(s) — 0 means the first screen "
                + "posts no notification here; see the verification doc for what that implies"
        )

        // Navigation push (mirrors demos/showcase/scenarios/navigation.yaml).
        app.descendants(matching: .any)["stable.row.3"].tap()
        XCTAssertTrue(app.descendants(matching: .any)["horse.title"].waitForExistence(timeout: 5))
        settle()
        XCTAssertGreaterThan(
            listener.transitionCount, coldLaunchCount,
            "navigation push did not report a screen-transition event"
        )
        let afterPush = listener.transitionCount

        app.navigationBars.buttons.firstMatch.tap()  // OS back button
        XCTAssertTrue(app.descendants(matching: .any)["stable.row.3"].waitForExistence(timeout: 5))
        settle()

        // Modal presentation: the Log tab's detented sheet (mirrors demos/showcase/scenarios/modals.yaml).
        app.descendants(matching: .any)
            .matching(NSPredicate(format: "label == %@ AND elementType == %ld", "Log", XCUIElement.ElementType.button.rawValue))
            .firstMatch.tap()
        XCTAssertTrue(app.descendants(matching: .any)["log.openFilter"].waitForExistence(timeout: 10))
        settle()
        let afterTabSwitch = listener.transitionCount
        XCTAssertGreaterThan(afterTabSwitch, afterPush, "tab switch did not report a screen-transition event")

        app.descendants(matching: .any)["log.openFilter"].tap()
        XCTAssertTrue(app.descendants(matching: .any)["log.sheet.title"].waitForExistence(timeout: 5))
        settle()
        XCTAssertGreaterThan(
            listener.transitionCount, afterTabSwitch,
            "modal presentation did not report a screen-transition event"
        )
        app.descendants(matching: .any)["log.sheet.close"].tap()
        XCTAssertTrue(app.descendants(matching: .any)["log.sheet.title"].waitForNonExistence(timeout: 5))
        settle()

        // Not-covered case (documented, not asserted strictly): an in-place data update. The
        // proposal expects at most `layoutChangedNotification`, often nothing — record what
        // actually happens rather than assuming it.
        let beforeToggle = listener.transitionCount
        app.descendants(matching: .any)["log.intense"].tap()
        settle()
        let afterToggle = listener.transitionCount
        XCTAssertEqual(
            afterToggle, beforeToggle,
            "an in-place data update (the 'Intense' toggle) reported a screen-transition event — "
                + "the proposal's boundary assumption was wrong; note this in the verification doc "
                + "rather than silently accepting it"
        )
    }
}
