"""Scenario spec — the structure normalized from natural language.

The package keeps the data shapes (`models`), parsing (`load`), compile-time expansion
(`expand`), tag selection (`select`), and serialization (`serialize`) in separate modules so a
change to one rarely touches the others (BE-0043). The full public API is re-exported here, so
`from bajutsu.scenario import Scenario, load_scenarios, ...` keeps working unchanged.
"""

from __future__ import annotations

from bajutsu.scenario.expand import (
    apply_setups,
    expand_components,
    expand_data,
    read_csv,
)
from bajutsu.scenario.load import load_component, load_scenario_file, load_scenarios
from bajutsu.scenario.models import (
    STEP_ACTIONS,
    Assertion,
    Background,
    CaptureRule,
    ClearClipboard,
    ClearKeychain,
    ClearStatusBar,
    Component,
    CountMatch,
    DismissAlerts,
    ExcludeRegion,
    Exists,
    Extract,
    ForEach,
    Gone,
    HttpRequest,
    If,
    LongPress,
    Mock,
    MockResponse,
    Network,
    NetworkFilter,
    OverrideStatusBar,
    Pinch,
    Point,
    Preconditions,
    Push,
    Redact,
    Relaunch,
    RequestMatch,
    Rotate,
    Scenario,
    ScenarioFile,
    Selector,
    SetLocation,
    Step,
    Swipe,
    TextMatch,
    Trigger,
    TypeText,
    Use,
    VisualMatch,
    Wait,
    WaitRequest,
)
from bajutsu.scenario.select import select_scenarios
from bajutsu.scenario.serialize import (
    dump_mocks,
    dump_scenario_file,
    dump_scenarios,
    scenario_dict,
)

__all__ = [
    "STEP_ACTIONS",
    "Assertion",
    "Background",
    "CaptureRule",
    "ClearClipboard",
    "ClearKeychain",
    "ClearStatusBar",
    "Component",
    "CountMatch",
    "DismissAlerts",
    "ExcludeRegion",
    "Exists",
    "Extract",
    "ForEach",
    "Gone",
    "HttpRequest",
    "If",
    "LongPress",
    "Mock",
    "MockResponse",
    "Network",
    "NetworkFilter",
    "OverrideStatusBar",
    "Pinch",
    "Point",
    "Preconditions",
    "Push",
    "Redact",
    "Relaunch",
    "RequestMatch",
    "Rotate",
    "Scenario",
    "ScenarioFile",
    "Selector",
    "SetLocation",
    "Step",
    "Swipe",
    "TextMatch",
    "Trigger",
    "TypeText",
    "Use",
    "VisualMatch",
    "Wait",
    "WaitRequest",
    "apply_setups",
    "dump_mocks",
    "dump_scenario_file",
    "dump_scenarios",
    "expand_components",
    "expand_data",
    "load_component",
    "load_scenario_file",
    "load_scenarios",
    "read_csv",
    "scenario_dict",
    "select_scenarios",
]
