// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import { test, expect } from '@playwright/test';

const BASE_URL = 'http://127.0.0.1:8787/index.html';

test.describe('Smoke Spec', () => {
  test('onboard, log in, and increment the counter', async ({ page }) => {
    await page.goto(BASE_URL);

    await page.getByTestId('onboarding.start').click();
    await page.getByTestId('auth.email').fill('a@b.com');
    await page.getByTestId('auth.password').fill('pw');
    await page.getByTestId('auth.submit').click();
    await expect(page.getByTestId('home.title')).toBeVisible({ timeout: 5000 });
    await page.getByTestId('counter.increment').click();
    await page.getByTestId('counter.increment').click();

    // expect
    await expect(page.getByTestId('home.title')).toBeVisible();
    await expect(page.getByTestId('counter.value')).toHaveValue('2');
  });

});
