#!/usr/bin/env bash
# Git merge driver for APM's committed generated output (BE-0390, mirroring BE-0043's uv.lock
# driver): apm.lock.yaml and the deployed .claude/skills/ tree.
#
# Both are `apm install` output, not hand-written, and both have the property that makes a
# line-by-line three-way merge wrong rather than merely noisy: two branches that edited the same
# skill conflict on generated bytes whose correct value is on neither side — it is whatever
# `apm install` writes from the merged source. Hand-resolving the deployed copy is the trap, since
# it looks like it worked while leaving a deployment that no longer matches its source, which
# surfaces later as an unexplained `make lint-skills` drift failure. So don't merge these files:
# regenerate them from .apm/skills/ and hand git the fresh bytes.
#
# Wired by `make hooks` / `make setup` as the `apm-generated` merge driver; `.gitattributes` maps
# both paths to it. apm reaches us through `uv run`, since apm-cli is a `dev` dependency rather than
# a separately installed tool, so a synced clone needs nothing extra for a merge to resolve. Git invokes us with the current/ours temp file (%A) that we must overwrite with
# the merged result, and the real pathname being merged (%P) — which is where `apm install` writes,
# so we copy from there. One `apm install` per conflicted file is redundant but cheap (~0.2s) and
# keeps the driver stateless; git gives it no way to know how many files a merge still has to go.
#
# What this writes is PROVISIONAL, exactly as merge-uv-lock.sh's output is: git runs every merge
# driver before it writes any merged file, so `apm install` reads the pre-merge .apm/skills/ tree.
# `make lint-skills` is the backstop — the role `uv lock --check` plays for uv.lock — and it fails
# until a post-merge `make skills` refreshes what this wrote. Every refusal below exits non-zero so
# git leaves the file conflicted rather than recording bytes we don't trust.
set -euo pipefail

merged="$1" # %A — git expects the resolved content written here
path="$2"   # %P — the pathname being merged, which is what `apm install` rewrites

if ! uv run --no-sync apm install --no-policy >/dev/null 2>&1; then
	echo "merge-apm-generated: 'uv run apm install' failed — run 'uv sync --group dev', fix the skill sources, then re-merge" >&2
	exit 1
fi

if [ ! -f "$path" ]; then
	echo "merge-apm-generated: 'apm install' wrote no $path — resolve the source, then re-merge" >&2
	exit 1
fi

cp "$path" "$merged"
