// Generated by bajutsu — do not edit by hand. Re-generate with `bajutsu codegen`.
import XCTest

final class GesturesuitestsUITests: XCTestCase {
  private let app = XCUIApplication()
  private func el(_ id: String) -> XCUIElement {
    app.descendants(matching: .any)[id]
  }
  private func byLabel(_ label: String) -> XCUIElement {
    app.descendants(matching: .any).matching(NSPredicate(format: "label == %@", label)).firstMatch
  }
  private func matchingId(_ glob: String) -> XCUIElementQuery {
    app.descendants(matching: .any).matching(NSPredicate(format: "identifier LIKE %@", glob))
  }

  func test_double_tap_increments() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "gestures"
    app.launch()

    XCTAssertEqual(el("gest.doubletap.value").value as? String, "0")
    el("gest.doubletap").doubleTap()

    // expect
    XCTAssertEqual(el("gest.doubletap.value").value as? String, "1")
  }

  func test_pinch_zooms_in() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "gestures"
    app.launch()

    el("gest.pinch").pinch(withScale: 2.0, velocity: 1.0)

    // expect
    XCTAssertEqual(el("gest.pinch.value").value as? String, "in")
  }

  func test_rotate_clockwise() {
    app.launchEnvironment["SAMPLE_UITEST"] = "1"
    app.launchEnvironment["SAMPLE_LOGGED_IN"] = "1"
    app.launchEnvironment["SAMPLE_TAB"] = "gestures"
    app.launch()

    el("gest.rotate").rotate(1.57, withVelocity: 1.0)

    // expect
    XCTAssertEqual(el("gest.rotate.value").value as? String, "cw")
  }

}
